; move ids
; indexes for:
; - Moves (see data/moves/moves.asm)
; - MoveNames (see data/moves/names.asm)
; - MoveDescriptions (see data/moves/descriptions.asm)
; - BattleAnimations (see data/moves/animations.asm)
	const_def
	const NO_MOVE      ; 00
	const POUND        ; 01
	const KARATE_CHOP  ; 02
	const DOUBLESLAP   ; 03
	const COMET_PUNCH  ; 04
	const MEGA_PUNCH   ; 05
	const PAY_DAY      ; 06
	const FIRE_PUNCH   ; 07
	const ICE_PUNCH    ; 08
	const THUNDERPUNCH ; 09
	const SCRATCH      ; 0a
	const VICEGRIP     ; 0b
	const GUILLOTINE   ; 0c
	const RAZOR_WIND   ; 0d
	const SWORDS_DANCE ; 0e
	const CUT          ; 0f
	const GUST         ; 10
	const WING_ATTACK  ; 11
	const WHIRLWIND    ; 12
	const FLY          ; 13
	const BIND         ; 14
	const SLAM         ; 15
	const VINE_WHIP    ; 16
	const STOMP        ; 17
	const DOUBLE_KICK  ; 18
	const MEGA_KICK    ; 19
	const JUMP_KICK    ; 1a
	const ROLLING_KICK ; 1b
	const SAND_ATTACK  ; 1c
	const HEADBUTT     ; 1d
	const HORN_ATTACK  ; 1e
	const FURY_ATTACK  ; 1f
	const HORN_DRILL   ; 20
	const TACKLE       ; 21
	const BODY_SLAM    ; 22
	const WRAP         ; 23
	const TAKE_DOWN    ; 24
	const THRASH       ; 25
	const DOUBLE_EDGE  ; 26
	const TAIL_WHIP    ; 27
	const POISON_STING ; 28
	const TWINEEDLE    ; 29
	const PIN_MISSILE  ; 2a
	const LEER         ; 2b
	const BITE         ; 2c
	const GROWL        ; 2d
	const ROAR         ; 2e
	const SING         ; 2f
	const SUPERSONIC   ; 30
	const SONICBOOM    ; 31
	const DISABLE      ; 32
	const ACID         ; 33
	const EMBER        ; 34
	const FLAMETHROWER ; 35
	const MIST         ; 36
	const WATER_GUN    ; 37
	const HYDRO_PUMP   ; 38
	const SURF         ; 39
	const ICE_BEAM     ; 3a
	const BLIZZARD     ; 3b
	const PSYBEAM      ; 3c
	const BUBBLEBEAM   ; 3d
	const AURORA_BEAM  ; 3e
	const HYPER_BEAM   ; 3f
	const PECK         ; 40
	const DRILL_PECK   ; 41
	const SUBMISSION   ; 42
	const LOW_KICK     ; 43
	const COUNTER      ; 44
	const SEISMIC_TOSS ; 45
	const STRENGTH     ; 46
	const ABSORB       ; 47
	const MEGA_DRAIN   ; 48
	const LEECH_SEED   ; 49
	const GROWTH       ; 4a
	const RAZOR_LEAF   ; 4b
	const SOLARBEAM    ; 4c
	const POISONPOWDER ; 4d
	const STUN_SPORE   ; 4e
	const SLEEP_POWDER ; 4f
	const PETAL_DANCE  ; 50
	const STRING_SHOT  ; 51
	const DRAGON_RAGE  ; 52
	const FIRE_SPIN    ; 53
	const THUNDERSHOCK ; 54
	const THUNDERBOLT  ; 55
	const THUNDER_WAVE ; 56
	const THUNDER      ; 57
	const ROCK_THROW   ; 58
	const EARTHQUAKE   ; 59
	const FISSURE      ; 5a
	const DIG          ; 5b
	const TOXIC        ; 5c
	const CONFUSION    ; 5d
	const PSYCHIC_M    ; 5e
	const HYPNOSIS     ; 5f
	const MEDITATE     ; 60
	const AGILITY      ; 61
	const QUICK_ATTACK ; 62
	const RAGE         ; 63
	const TELEPORT     ; 64
	const NIGHT_SHADE  ; 65
	const MIMIC        ; 66
	const SCREECH      ; 67
	const DOUBLE_TEAM  ; 68
	const RECOVER      ; 69
	const HARDEN       ; 6a
	const MINIMIZE     ; 6b
	const SMOKESCREEN  ; 6c
	const CONFUSE_RAY  ; 6d
	const WITHDRAW     ; 6e
	const DEFENSE_CURL ; 6f
	const BARRIER      ; 70
	const LIGHT_SCREEN ; 71
	const HAZE         ; 72
	const REFLECT      ; 73
	const FOCUS_ENERGY ; 74
	const BIDE         ; 75
	const METRONOME    ; 76
	const MIRROR_MOVE  ; 77
	const SELFDESTRUCT ; 78
	const EGG_BOMB     ; 79
	const LICK         ; 7a
	const SMOG         ; 7b
	const SLUDGE       ; 7c
	const BONE_CLUB    ; 7d
	const FIRE_BLAST   ; 7e
	const WATERFALL    ; 7f
	const CLAMP        ; 80
	const SWIFT        ; 81
	const SKULL_BASH   ; 82
	const SPIKE_CANNON ; 83
	const CONSTRICT    ; 84
	const AMNESIA      ; 85
	const KINESIS      ; 86
	const SOFTBOILED   ; 87
	const HI_JUMP_KICK ; 88
	const GLARE        ; 89
	const DREAM_EATER  ; 8a
	const POISON_GAS   ; 8b
	const BARRAGE      ; 8c
	const LEECH_LIFE   ; 8d
	const LOVELY_KISS  ; 8e
	const SKY_ATTACK   ; 8f
	const TRANSFORM    ; 90
	const BUBBLE       ; 91
	const DIZZY_PUNCH  ; 92
	const SPORE        ; 93
	const FLASH        ; 94
	const PSYWAVE      ; 95
	const SPLASH       ; 96
	const ACID_ARMOR   ; 97
	const CRABHAMMER   ; 98
	const EXPLOSION    ; 99
	const FURY_SWIPES  ; 9a
	const BONEMERANG   ; 9b
	const REST         ; 9c
	const ROCK_SLIDE   ; 9d
	const HYPER_FANG   ; 9e
	const SHARPEN      ; 9f
	const CONVERSION   ; a0
	const TRI_ATTACK   ; a1
	const SUPER_FANG   ; a2
	const SLASH        ; a3
	const SUBSTITUTE   ; a4
	const STRUGGLE     ; a5
	const SKETCH       ; a6
	const TRIPLE_KICK  ; a7
	const THIEF        ; a8
	const SPIDER_WEB   ; a9
	const MIND_READER  ; aa
	const NIGHTMARE    ; ab
	const FLAME_WHEEL  ; ac
	const SNORE        ; ad
	const CURSE        ; ae
	const FLAIL        ; af
	const CONVERSION2  ; b0
	const AEROBLAST    ; b1
	const COTTON_SPORE ; b2
	const REVERSAL     ; b3
	const SPITE        ; b4
	const POWDER_SNOW  ; b5
	const PROTECT      ; b6
	const MACH_PUNCH   ; b7
	const SCARY_FACE   ; b8
	const FAINT_ATTACK ; b9
	const SWEET_KISS   ; ba
	const BELLY_DRUM   ; bb
	const SLUDGE_BOMB  ; bc
	const MUD_SLAP     ; bd
	const OCTAZOOKA    ; be
	const SPIKES       ; bf
	const ZAP_CANNON   ; c0
	const FORESIGHT    ; c1
	const DESTINY_BOND ; c2
	const PERISH_SONG  ; c3
	const ICY_WIND     ; c4
	const DETECT       ; c5
	const BONE_RUSH    ; c6
	const LOCK_ON      ; c7
	const OUTRAGE      ; c8
	const SANDSTORM    ; c9
	const GIGA_DRAIN   ; ca
	const ENDURE       ; cb
	const CHARM        ; cc
	const ROLLOUT      ; cd
	const FALSE_SWIPE  ; ce
	const SWAGGER      ; cf
	const MILK_DRINK   ; d0
	const SPARK        ; d1
	const FURY_CUTTER  ; d2
	const STEEL_WING   ; d3
	const MEAN_LOOK    ; d4
	const ATTRACT      ; d5
	const SLEEP_TALK   ; d6
	const HEAL_BELL    ; d7
	const RETURN       ; d8
	const PRESENT      ; d9
	const FRUSTRATION  ; da
	const SAFEGUARD    ; db
	const PAIN_SPLIT   ; dc
	const SACRED_FIRE  ; dd
	const MAGNITUDE    ; de
	const DYNAMICPUNCH ; df
	const MEGAHORN     ; e0
	const DRAGONBREATH ; e1
	const BATON_PASS   ; e2
	const ENCORE       ; e3
	const PURSUIT      ; e4
	const RAPID_SPIN   ; e5
	const SWEET_SCENT  ; e6
	const IRON_TAIL    ; e7
	const METAL_CLAW   ; e8
	const VITAL_THROW  ; e9
	const MORNING_SUN  ; ea
	const SYNTHESIS    ; eb
	const MOONLIGHT    ; ec
	const HIDDEN_POWER ; ed
	const CROSS_CHOP   ; ee
	const TWISTER      ; ef
	const RAIN_DANCE   ; f0
	const SUNNY_DAY    ; f1
	const CRUNCH       ; f2
	const MIRROR_COAT  ; f3
	const PSYCH_UP     ; f4
	const EXTREMESPEED ; f5
	const ANCIENTPOWER ; f6
	const SHADOW_BALL  ; f7
	const FUTURE_SIGHT ; f8
	const ROCK_SMASH   ; f9
	const WHIRLPOOL    ; fa
	const BEAT_UP      ; fb
;
	const BURN_UP      ;  fc
	const STRENGTH_SAP ;  fd
	const U_TURN       ;  fe
	const MOVE_FF      ;  ff, don't use
	const MOVE_100     ; 100, don't use
	const FREEZE_DRY   ; 101
	const FLYING_PRESS ; 102
	const VOLT_SWITCH  ; 103
	const CIRCLE_THROW ; 104
	const DRAGON_TAIL  ; 105
	const AVALANCHE    ; 106
	const REVENGE      ; 107
	const KNOCK_OFF    ; 108
	const BUG_BUZZ     ; 109
	const LUNGE        ; 10a
	const QUIVER_DANCE ; 10b
	const SIGNAL_BEAM  ; 10c
	const SILVER_WIND  ; 10d
	const X_SCISSOR    ; 10e
	const DARK_PULSE   ; 10f
	const FOUL_PLAY    ; 110
	const NASTY_PLOT   ; 111
	const DISCHARGE    ; 112
	const ELECTROWEB   ; 113
	const NUZZLE       ; 114
	const SHOCK_WAVE   ; 115
	const WILD_CHARGE  ; 116
	const DRAGON_CLAW  ; 117
	const DRAGON_DANCE ; 118
	const DRAGON_DARTS ; 119
	const DRAGON_PULSE ; 11a
	const DRAGON_RUSH  ; 11b
	const DUAL_CHOP    ; 11c
	const DAZZLY_GLEAM ; 11d
	const DISARMINGCRY ; 11e
	const DRAININGKISS ; 11f
	const FAIRY_WIND   ; 120
	const MOONBLAST    ; 121
	const NATURES_CURE ; 122
	const PLAY_ROUGH   ; 123
	const SPIRIT_BREAK ; 124
	const STRANGESTEAM ; 125
	const APPLE_ACID   ; 126
	const BULLET_SEED  ; 127
	const ENERGY_BALL  ; 128
	const GRAV_APPLE   ; 129
	const HORN_LEECH   ; 12a
	const LEAF_BLADE   ; 12b
	const LEAFAGE      ; 12c
	const MAGICAL_LEAF ; 12d
	const PETALBLIZARD ; 12e
	const POWER_WHIP   ; 12f
	const SOLAR_BLADE  ; 130
	const WOOD_HAMMER  ; 131
	const AQUA_JET     ; 132
	const AQUA_TAIL    ; 133
	const FISHIOUSREND ; 134
	const BOLT_BEAK    ; 135
	const SUPER_BLOOM  ; 136
	const MELTDOWN     ; 137
	const FLIP_TURN    ; 138
	const LIQUIDATION  ; 139
	const MUDDY_WATER  ; 13a
	const SCALD        ; 13b
	const SOAK         ; 13c
	const STEAMRUPTION ; 13d
	const WATERSHURIKN ; 13e
	const STEALTHROCKS ; 13f
	const TOXIC_SPIKES ; 140
	const SCALE_CLANG  ; 141
	const H_SPACE_FURY ; 142
	const DRACO_METEOR ; 143
	const OVERHEAT     ; 144
	const LEAF_STORM   ; 145
	const PSYCHO_BOOST ; 146
	const FLEUR_CANNON ; 147
	const CLOSE_COMBAT ; 148
	const DRAGONASCENT ; 149
	const HAMMER_ARM   ; 14a
	const SUPERPOWER   ; 14b
	const ICE_HAMMER   ; 14c
	const V_CREATE     ; 14d
	const FELL_STINGER ; 14e
	const FAKE_OUT     ; 14f
	const FIRST_IMP    ; 150
	const GEOMANCY     ; 151
	const ACROBATICS   ; 152
	const FACADE       ; 153
	const HEX          ; 154
	const VENOSHOCK    ; 155
	const PARTING_SHOT ; 156
	const CHARGE_BEAM  ; 157
	const THUNDER_FANG ; 158
	const AURA_SPHERE  ; 159
	const BRICK_BREAK  ; 15a
	const BULK_UP      ; 15b
	const DRAIN_PUNCH  ; 15c
	const FOCUS_BLAST  ; 15d
	const POWERUPPUNCH ; 15e
	const SKY_UPPERCUT ; 15f
	const STORM_THROW  ; 160
	const VACUUM_WAVE  ; 161
	const WAKE_UP_SLAP ; 162
	const AERIAL_ACE   ; 163
	const AIR_SLASH    ; 164
	const BOUNCE       ; 165
	const BRAVE_BIRD   ; 166
	const DEFOG        ; 167
	const DUALWINGBEAT ; 168
	const FEATHERDANCE ; 169
	const HURRICANE    ; 16a
	const ROOST        ; 16b
	const BOOMBURST    ; 16c
	const COURT_CHANGE ; 16d
	const ENDEAVOR     ; 16e
	const GIGA_IMPACT  ; 16f
	const HYPER_VOICE  ; 170
	const REFLECT_TYPE ; 171
	const SHELL_SMASH  ; 172
	const SLACK_OFF    ; 173
	const TRUMP_CARD   ; 174
	const WORK_UP      ; 175
	const BULLDOZE     ; 176
	const DRILL_RUN    ; 177
	const EARTH_POWER  ; 178
	const SCORCHINSAND ; 179
	const THSND_ARROWS ; 17a
	const THSND_WAVES  ; 17b
	const ACCELEROCK   ; 17c
	const DIAMONDSTORM ; 17d
	const HEAD_SMASH   ; 17e
	const METEOR_BEAM  ; 17f
	const POWER_GEM    ; 180
	const ROCK_BLAST   ; 181
	const ROCK_POLISH  ; 182
	const SMACK_DOWN   ; 183
	const STONE_EDGE   ; 184
	const ASTONISH     ; 185
	const OMINOUS_WIND ; 186
	const PHANTOMFORCE ; 187
	const POLTERGEIST  ; 188
	const SHADOW_BONE  ; 189
	const SHADOW_CLAW  ; 18a
	const SHADOW_FORCE ; 18b
	const SHADOW_PUNCH ; 18c
	const SHADOW_SNEAK ; 18d
	const SPECTRLTHIEF ; 18e
	const SPIRITSHACKL ; 18f
	const BLAST_BURN   ; 190
	const BLAZE_KICK   ; 191
	const BLUE_FLARE   ; 192
	const BURNING_ENVY ; 193
	const ERUPTION     ; 194
	const WATER_SPOUT  ; 195
	const FIERY_DANCE  ; 196
	const FIRE_FANG    ; 197
	const FIRE_LASH    ; 198
	const FLAME_CHARGE ; 199
	const FLARE_BLITZ  ; 19a
	const INCINERATE   ; 19b
	const INFERNO      ; 19c
	const LAVA_PLUME   ; 19d
	const MAGMA_STORM  ; 19e
	const MIND_BLOWN   ; 19f
	const MYSTICALFIRE ; 1a0
	const SEARING_SHOT ; 1a1
	const WILL_O_WISP  ; 1a2
	const ANCHOR_SHOT  ; 1a3
	const BULLET_PUNCH ; 1a4
	const FLASH_CANNON ; 1a5
	const GEAR_GRIND   ; 1a6
	const GYRO_BALL    ; 1a7
	const IRON_DEFENSE ; 1a8
	const IRON_HEAD    ; 1a9
	const KINGS_SHIELD ; 1aa
	const MAGNET_BOMB  ; 1ab
	const METEOR_MASH  ; 1ac
	const MIRROR_SHOT  ; 1ad
	const SHIFT_GEAR   ; 1ae
	const SMART_STRIKE ; 1af
	const STEEL_BEAM   ; 1b0
	const CALM_MIND    ; 1b1
	const COSMIC_POWER ; 1b2
	const EXTRASENSORY ; 1b3
	const HEART_STAMP  ; 1b4
	const HEART_SWAP   ; 1b5
	const H_SPACE_HOLE ; 1b6
	const LUSTER_PURGE ; 1b7
	const MIST_BALL    ; 1b8
	const PRISM_LASER  ; 1b9
	const PSYCHIC_FANG ; 1ba
	const PSYCHO_CUT   ; 1bb
	const PSYCHO_SHIFT ; 1bc
	const PSYSHOCK     ; 1bd
	const PSYSTRIKE    ; 1be
	const STORED_POWER ; 1bf
	const SYNCHRONOISE ; 1c0
	const TRICK        ; 1c1
	const TRICK_ROOM   ; 1c2
	const ZEN_HEADBUTT ; 1c3
	const STICKY_WEB   ; 1c4
	const ACID_SPRAY   ; 1c5
	const CLEAR_SMOG   ; 1c6
	const COIL         ; 1c7
	const CROSS_POISON ; 1c8
	const POISON_FANG  ; 1c9
	const POISON_JAB   ; 1ca
	const POISON_TAIL  ; 1cb
	const SLUDGE_WAVE  ; 1cc
	const TOXIC_THREAD ; 1cd
	const VENOM_DRENCH ; 1ce
	const GUNK_SHOT    ; 1cf
	const ARM_THRUST   ; 1d0
	const FINAL_GAMBIT ; 1d1
	const FORCE_PALM   ; 1d2
	const OBLIVIONWING ; 1d3
	const ATTACK_ORDER ; 1d4
	const DEFEND_ORDER ; 1d5
	const HEAL_ORDER   ; 1d6
	const INFESTATION  ; 1d7
	const SKITTERSMACK ; 1d8
	const STRUGGLE_BUG ; 1d9
	const STEAMROLLER  ; 1da
	const BOLT_STRIKE  ; 1db
	const ERIE_IMPULSE ; 1dc
	const ZING_ZAP     ; 1dd
	const SPACIAL_REND ; 1de
	const ROAR_OF_TIME ; 1df
	const BRUTAL_SWING ; 1e0
	const FAKE_TEARS   ; 1e1
	const SECRET_SWORD ; 1e2
	const SACRED_SWORD ; 1e3
	const CHIP_AWAY    ; 1e4
	const DARK_LARIAT  ; 1e5
	const FROST_BREATH ; 1e6
	const GLACIATE     ; 1e7
	const ICE_BALL     ; 1e8
	const ICE_FANG     ; 1e9
	const ICE_SHARD    ; 1ea
	const ICICLE_CRASH ; 1eb
	const ICICLE_SPEAR ; 1ec
	const TRIPLE_AXEL  ; 1ed
	const THUNDER_CAGE ; 1ee
	const DRAKE_ENERGY ; 1ef
	const FREEZE_GLARE ; 1f0
	const FIERY_WRATH  ; 1f1
	const THUNDER_KICK ; 1f2
	const WICKED_BLOW  ; 1f3
	const SWITCHEROO   ; 1f4
	const SNARL        ; 1f5
	const POWER_TRIP   ; 1f6
	const SEED_FLARE   ; 1f7
	const TROP_KICK    ; 1f8
	const NEEDLE_ARM   ; 1f9
	const TAUNT        ; 1fa
	const TAILWIND     ; 1fb
	const HONE_CLAWS   ; 1fc
	const NIGHT_DAZE   ; 1fd
	const NIGHT_SLASH  ; 1fe
	const MOVE_1FF     ; 1ff, don't use
	const MOVE_200     ; 200, don't use
	const CRUSH_GRIP   ; 201
	const WRING_OUT    ; 202
	const MEMENTO      ; 203
	const WEATHER_BALL ; 204
	const AROMATHERAPY ; 205
	const BLOCK        ; 206
	const COVET        ; 207
	const CRUSH_CLAW   ; 208
	const HOWL         ; 209
	const FEINT        ; 20a
	const ELECTRO_BALL ; 20b
	const HEAD_CHARGE  ; 20c
	const LEAF_TORNADO ; 20d
	const LOW_SWEEP    ; 20e
	const RAZOR_SHELL  ; 20f
	const BABYDOLLEYES ; 210
	const LANDS_WRATH  ; 211
	const NO_SURRENDER ; 212
	const BREAK_SWIPE  ; 213
	const PRECIPICE    ; 214
	const SUCKER_PUNCH ; 215
	const HAIL         ; 216
	const AURORA_VEIL  ; 217
	const PUNISHMENT   ; 218
	const SNATCH       ; 219
	const TOPSY_TURVY  ; 21a
	const PURIFY       ; 21b
	const OCTOLOCK     ; 21c
	const STAR_ASSAULT ; 21d
	const VOLT_TACKLE  ; 21e
	const BUG_BITE     ; 21f
	const MUD_BOMB     ; 220
	const MUD_SHOT     ; 220
	const ROCK_TOMB    ; 222
	const HEAT_WAVE    ; 223

; This constant is used by engine/battle/move_effects/metronome.asm, when it randomly
; selects a move.
; Also by BattleAnimRunScript, to decide whether it should make the hud disappear.
NUM_ATTACKS EQU const_value + -1

; Battle animations use the same constants as the moves up to this point
	const ANIM_SWEET_SCENT_2     ; 
	const ANIM_THROW_POKE_BALL   ; 
	const ANIM_SEND_OUT_MON      ; 
	const ANIM_RETURN_MON        ; 
	const ANIM_CONFUSED          ; 
	const ANIM_SLP               ; 
	const ANIM_BRN               ; 
	const ANIM_PSN               ; 
	const ANIM_SAP               ; 
	const ANIM_FRZ               ; 
	const ANIM_PAR               ; 
	const ANIM_IN_LOVE           ; 
	const ANIM_IN_SANDSTORM      ; 
	const ANIM_IN_HAIL           ; 
	const ANIM_IN_NIGHTMARE      ; 
	const ANIM_IN_WHIRLPOOL      ; 
	const ANIM_MEGA_EVOLVE
; battle anims
	const ANIM_MISS              ; 
	const ANIM_ENEMY_DAMAGE      ; 
	const ANIM_ENEMY_STAT_DOWN   ; 
	const ANIM_PLAYER_STAT_DOWN  ; 
	const ANIM_PLAYER_DAMAGE     ; 
	const ANIM_WOBBLE            ; 
	const ANIM_SHAKE             ; 
	const ANIM_HIT_CONFUSION     ; 

; wNumHits uses offsets from ANIM_MISS
	const_def
	const BATTLEANIM_NONE
	const BATTLEANIM_ENEMY_DAMAGE
	const BATTLEANIM_ENEMY_STAT_DOWN
	const BATTLEANIM_PLAYER_STAT_DOWN
	const BATTLEANIM_PLAYER_DAMAGE
	const BATTLEANIM_WOBBLE
	const BATTLEANIM_SHAKE
	const BATTLEANIM_HIT_CONFUSION
