AnimationPointers:
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw CaterpieAnimation
	dw MetapodAnimation
	dw ButterfreeAnimation
	dw WeedleAnimation
	dw KakunaAnimation
	dw BeedrillAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw RattataAnimation
	dw RaticateAnimation
	dw SpearowAnimation
	dw FearowAnimation
	dw EkansAnimation
	dw ArbokAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw SandshrewAnimation
	dw SandslashAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw VulpixAnimation
	dw NinetalesAnimation
	dw JigglypuffAnimation
	dw WigglytuffAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw OddishAnimation
	dw GloomAnimation
	dw VileplumeAnimation
	dw ParasAnimation
	dw ParasectAnimation
	dw VenonatAnimation
	dw VenomothAnimation
	dw DiglettAnimation
	dw DugtrioAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw PsyduckAnimation
	dw GolduckAnimation
	dw MankeyAnimation
	dw PrimeapeAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw PoliwagAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw MachopAnimation
	dw MachokeAnimation
	dw MachampAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw FarfetchDAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw SeelAnimation
	dw DewgongAnimation
	dw GrimerAnimation
	dw MukAnimation
	dw ShellderAnimation
	dw CloysterAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw DrowzeeAnimation
	dw HypnoAnimation
	dw KrabbyAnimation
	dw KinglerAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw HitmonleeAnimation
	dw HitmonchanAnimation
	dw LickitungAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw ChanseyAnimation
	dw TangelaAnimation
	dw KangaskhanAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw GoldeenAnimation
	dw SeakingAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MrMimeAnimation
	dw ScytherAnimation
	dw JynxAnimation
	dw ElectabuzzAnimation
	dw MagmarAnimation
	dw PinsirAnimation
	dw TaurosAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw OmanyteAnimation
	dw OmastarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuAnimation
	dw CleffaAnimation
	dw IgglybuffAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw BellossomAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw AipomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MurkrowAnimation
	dw SlowkingAnimation
	dw MisdreavusAnimation
	dw UnownAnimation
	dw WobbuffetAnimation
	dw GirafarigAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw DunsparceAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw QwilfishAnimation
	dw ScizorAnimation
	dw ShuckleAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw CorsolaAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw StantlerAnimation
	dw SmeargleAnimation
	dw TyrogueAnimation
	dw HitmontopAnimation
	dw SmoochumAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw CelebiAnimation
	dw CelebiAnimation
	dw 0, 0, 0
	dw YamaskAnimation
	dw CofagrigusAnimation
	dw FroakieAnimation
	dw FrogadierAnimation
	dw GreninjaAnimation
	dw NincadaAnimation
	dw NinjaskAnimation
	dw ShedinjaAnimation
	dw Mon_109Animation
	dw Mon_10AAnimation
	dw Mon_10BAnimation
	dw Mon_10CAnimation
	dw Mon_10DAnimation
	dw Mon_10EAnimation
	dw Mon_10FAnimation
	dw Mon_110Animation
	dw Mon_111Animation
	dw Mon_112Animation
	dw Mon_113Animation
	dw Mon_114Animation
	dw Mon_115Animation
	dw Mon_116Animation
	dw Mon_117Animation
	dw Mon_118Animation
	dw Mon_119Animation
	dw Mon_11AAnimation
	dw Mon_11BAnimation
	dw Mon_11CAnimation
	dw Mon_11DAnimation
	dw Mon_11EAnimation
	dw Mon_11FAnimation
	dw Mon_120Animation
	dw Mon_121Animation
	dw Mon_122Animation
	dw Mon_123Animation
	dw Mon_124Animation
	dw Mon_125Animation
	dw Mon_126Animation
	dw Mon_127Animation
	dw Mon_128Animation
	dw Mon_129Animation
	dw Mon_12AAnimation
	dw Mon_12BAnimation
	dw Mon_12CAnimation
	dw Mon_12DAnimation
	dw Mon_12EAnimation
	dw Mon_12FAnimation
	dw Mon_130Animation
	dw Mon_131Animation
	dw Mon_132Animation
	dw Mon_133Animation
	dw Mon_134Animation
	dw Mon_135Animation
	dw Mon_136Animation
	dw Mon_137Animation
	dw Mon_138Animation
	dw Mon_139Animation
	dw Mon_13AAnimation
	dw Mon_13BAnimation
	dw Mon_13CAnimation
	dw Mon_13DAnimation
	dw Mon_13EAnimation
	dw Mon_13FAnimation
	dw Mon_140Animation
	dw Mon_141Animation
	dw Mon_142Animation
	dw Mon_143Animation
	dw Mon_144Animation
	dw Mon_145Animation
	dw Mon_146Animation
	dw Mon_147Animation
	dw Mon_148Animation
	dw Mon_149Animation
	dw Mon_14AAnimation
	dw Mon_14BAnimation
	dw Mon_14CAnimation
	dw Mon_14DAnimation
	dw Mon_14EAnimation
	dw Mon_14FAnimation
	dw Mon_150Animation
	dw Mon_151Animation
	dw Mon_152Animation
	dw Mon_153Animation
	dw Mon_154Animation
	dw Mon_155Animation
	dw Mon_156Animation
	dw Mon_157Animation
	dw Mon_158Animation
	dw Mon_159Animation
	dw Mon_15AAnimation
	dw Mon_15BAnimation
	dw Mon_15CAnimation
	dw Mon_15DAnimation
	dw Mon_15EAnimation
	dw Mon_16FAnimation
	dw Mon_160Animation
	dw Mon_161Animation
	dw Mon_162Animation
	dw Mon_163Animation
	dw Mon_164Animation
	dw Mon_165Animation
	dw Mon_166Animation
	dw Mon_167Animation
	dw Mon_168Animation
	dw Mon_169Animation
	dw Mon_16AAnimation
	dw Mon_16BAnimation
	dw Mon_16CAnimation
	dw Mon_16DAnimation
	dw Mon_16EAnimation
	dw Mon_16FAnimation
	dw Mon_170Animation
	dw Mon_171Animation
	dw Mon_172Animation
	dw Mon_173Animation
	dw Mon_174Animation
	dw Mon_175Animation
	dw Mon_176Animation
	dw Mon_177Animation
	dw Mon_178Animation
	dw Mon_179Animation
	dw Mon_17AAnimation
	dw Mon_17BAnimation
	dw Mon_17CAnimation
	dw Mon_17DAnimation
	dw Mon_17EAnimation
	dw Mon_17FAnimation
	dw Mon_180Animation
	dw Mon_181Animation
	dw Mon_182Animation
	dw Mon_183Animation
	dw Mon_184Animation
	dw Mon_185Animation
	dw Mon_186Animation
	dw Mon_187Animation
	dw Mon_188Animation
	dw Mon_189Animation
	dw Mon_18AAnimation
	dw Mon_18BAnimation
	dw Mon_18CAnimation
	dw Mon_18DAnimation
	dw Mon_18EAnimation
	dw Mon_18FAnimation
	dw Mon_190Animation
	dw Mon_191Animation
	dw Mon_192Animation
	dw Mon_193Animation
	dw Mon_194Animation
	dw Mon_195Animation
	dw Mon_196Animation
	dw Mon_197Animation
	dw Mon_198Animation
	dw Mon_199Animation
	dw Mon_19AAnimation
	dw Mon_19BAnimation
	dw Mon_19CAnimation
	dw Mon_19DAnimation
	dw Mon_19EAnimation
	dw Mon_19FAnimation
	dw Mon_1A0Animation
	dw Mon_1A1Animation
	dw Mon_1A2Animation
	dw Mon_1A3Animation
	dw Mon_1A4Animation
	dw Mon_1A5Animation
	dw Mon_1A6Animation
	dw Mon_1A7Animation
	dw Mon_1A8Animation
	dw Mon_1A9Animation
	dw Mon_1AAAnimation
	dw Mon_1ABAnimation
	dw Mon_1ACAnimation
	dw Mon_1ADAnimation
	dw Mon_1AEAnimation
	dw Mon_1AFAnimation
	dw Mon_1B0Animation
	dw Mon_1B1Animation
	dw Mon_1B2Animation
	dw Mon_1B3Animation
	dw Mon_1B4Animation
	dw Mon_1B5Animation
	dw Mon_1B6Animation
	dw Mon_1B7Animation
	dw Mon_1B8Animation
	dw Mon_1B9Animation
	dw Mon_1BAAnimation
	dw Mon_1BBAnimation
	dw Mon_1BCAnimation
	dw Mon_1BDAnimation
	dw Mon_1BEAnimation
	dw Mon_1BFAnimation
	dw Mon_1C0Animation
	dw Mon_1C1Animation
	dw Mon_1C2Animation
	dw Mon_1C3Animation
	dw Mon_1C4Animation
	dw Mon_1C5Animation
	dw Mon_1C6Animation
	dw Mon_1C7Animation
	dw Mon_1C8Animation
	dw Mon_1C9Animation
	dw Mon_1CAAnimation
	dw Mon_1CBAnimation
	dw Mon_1CCAnimation
	dw Mon_1CDAnimation
	dw Mon_1CEAnimation
	dw Mon_1CFAnimation
	dw Mon_1D0Animation
	dw Mon_1D1Animation
	dw Mon_1D2Animation
	dw Mon_1D3Animation
	dw Mon_1D4Animation
	dw Mon_1D5Animation
	dw Mon_1D6Animation
	dw Mon_1D7Animation
	dw Mon_1D8Animation
	dw Mon_1D9Animation
	dw Mon_1DAAnimation
	dw Mon_1DBAnimation
	dw Mon_1DCAnimation
	dw Mon_1DDAnimation
	dw Mon_1DEAnimation
	dw Mon_1DFAnimation
	dw Mon_1E0Animation
	dw Mon_1E1Animation
	dw Mon_1E2Animation
	dw Mon_1E3Animation
	dw Mon_1E4Animation
	dw Mon_1E5Animation
	dw Mon_1E6Animation
	dw Mon_1E7Animation
	dw Mon_1E8Animation
	dw Mon_1E9Animation
	dw Mon_1EAAnimation
	dw Mon_1EBAnimation
	dw Mon_1ECAnimation
	dw Mon_1EDAnimation
	dw Mon_1EEAnimation
	dw Mon_1EFAnimation
	dw Mon_1F0Animation
	dw Mon_1F1Animation
	dw Mon_1F2Animation
	dw Mon_1F3Animation
	dw Mon_1F4Animation
	dw Mon_1F5Animation
	dw Mon_1F6Animation
	dw Mon_1F7Animation
	dw Mon_1F8Animation
	dw Mon_1F9Animation
	dw Mon_1FAAnimation
	dw Mon_1FBAnimation
	dw Mon_1FCAnimation
	dw Mon_1FDAnimation
