BitmasksPointers:
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw FarfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw TyrogueBitmasks
	dw HitmontopBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw CelebiBitmasks
	dw CelebiBitmasks
	dw 0, 0, 0
	dw YamaskBitmasks
	dw CofagrigusBitmasks
	dw FroakieBitmasks
	dw FrogadierBitmasks
	dw GreninjaBitmasks
	dw NincadaBitmasks
	dw NinjaskBitmasks
	dw ShedinjaBitmasks
	dw Mon_109Bitmasks
	dw Mon_10ABitmasks
	dw Mon_10BBitmasks
	dw Mon_10CBitmasks
	dw Mon_10DBitmasks
	dw Mon_10EBitmasks
	dw Mon_10FBitmasks
	dw Mon_110Bitmasks
	dw Mon_111Bitmasks
	dw Mon_112Bitmasks
	dw Mon_113Bitmasks
	dw Mon_114Bitmasks
	dw Mon_115Bitmasks
	dw Mon_116Bitmasks
	dw Mon_117Bitmasks
	dw Mon_118Bitmasks
	dw Mon_119Bitmasks
	dw Mon_11ABitmasks
	dw Mon_11BBitmasks
	dw Mon_11CBitmasks
	dw Mon_11DBitmasks
	dw Mon_11EBitmasks
	dw Mon_11FBitmasks
	dw Mon_120Bitmasks
	dw Mon_121Bitmasks
	dw Mon_122Bitmasks
	dw Mon_123Bitmasks
	dw Mon_124Bitmasks
	dw Mon_125Bitmasks
	dw Mon_126Bitmasks
	dw Mon_127Bitmasks
	dw Mon_128Bitmasks
	dw Mon_129Bitmasks
	dw Mon_12ABitmasks
	dw Mon_12BBitmasks
	dw Mon_12CBitmasks
	dw Mon_12DBitmasks
	dw Mon_12EBitmasks
	dw Mon_12FBitmasks
	dw Mon_130Bitmasks
	dw Mon_131Bitmasks
	dw Mon_132Bitmasks
	dw Mon_133Bitmasks
	dw Mon_134Bitmasks
	dw Mon_135Bitmasks
	dw Mon_136Bitmasks
	dw Mon_137Bitmasks
	dw Mon_138Bitmasks
	dw Mon_139Bitmasks
	dw Mon_13ABitmasks
	dw Mon_13BBitmasks
	dw Mon_13CBitmasks
	dw Mon_13DBitmasks
	dw Mon_13EBitmasks
	dw Mon_13FBitmasks
	dw Mon_140Bitmasks
	dw Mon_141Bitmasks
	dw Mon_142Bitmasks
	dw Mon_143Bitmasks
	dw Mon_144Bitmasks
	dw Mon_145Bitmasks
	dw Mon_146Bitmasks
	dw Mon_147Bitmasks
	dw Mon_148Bitmasks
	dw Mon_149Bitmasks
	dw Mon_14ABitmasks
	dw Mon_14BBitmasks
	dw Mon_14CBitmasks
	dw Mon_14DBitmasks
	dw Mon_14EBitmasks
	dw Mon_14FBitmasks
	dw Mon_150Bitmasks
	dw Mon_151Bitmasks
	dw Mon_152Bitmasks
	dw Mon_153Bitmasks
	dw Mon_154Bitmasks
	dw Mon_155Bitmasks
	dw Mon_156Bitmasks
	dw Mon_157Bitmasks
	dw Mon_158Bitmasks
	dw Mon_159Bitmasks
	dw Mon_15ABitmasks
	dw Mon_15BBitmasks
	dw Mon_15CBitmasks
	dw Mon_15DBitmasks
	dw Mon_15EBitmasks
	dw Mon_15FBitmasks
	dw Mon_160Bitmasks
	dw Mon_161Bitmasks
	dw Mon_162Bitmasks
	dw Mon_163Bitmasks
	dw Mon_164Bitmasks
	dw Mon_165Bitmasks
	dw Mon_166Bitmasks
	dw Mon_167Bitmasks
	dw Mon_168Bitmasks
	dw Mon_169Bitmasks
	dw Mon_16ABitmasks
	dw Mon_16BBitmasks
	dw Mon_16CBitmasks
	dw Mon_16DBitmasks
	dw Mon_16EBitmasks
	dw Mon_16FBitmasks
	dw Mon_170Bitmasks
	dw Mon_171Bitmasks
	dw Mon_172Bitmasks
	dw Mon_173Bitmasks
	dw Mon_174Bitmasks
	dw Mon_175Bitmasks
	dw Mon_176Bitmasks
	dw Mon_177Bitmasks
	dw Mon_178Bitmasks
	dw Mon_179Bitmasks
	dw Mon_17ABitmasks
	dw Mon_17BBitmasks
	dw Mon_17CBitmasks
	dw Mon_17DBitmasks
	dw Mon_17EBitmasks
	dw Mon_17FBitmasks
	dw Mon_180Bitmasks
	dw Mon_181Bitmasks
	dw Mon_182Bitmasks
	dw Mon_183Bitmasks
	dw Mon_184Bitmasks
	dw Mon_185Bitmasks
	dw Mon_186Bitmasks
	dw Mon_187Bitmasks
	dw Mon_188Bitmasks
	dw Mon_189Bitmasks
	dw Mon_18ABitmasks
	dw Mon_18BBitmasks
	dw Mon_18CBitmasks
	dw Mon_18DBitmasks
	dw Mon_18EBitmasks
	dw Mon_18FBitmasks
	dw Mon_190Bitmasks
	dw Mon_191Bitmasks
	dw Mon_192Bitmasks
	dw Mon_193Bitmasks
	dw Mon_194Bitmasks
	dw Mon_195Bitmasks
	dw Mon_196Bitmasks
	dw Mon_197Bitmasks
	dw Mon_198Bitmasks
	dw Mon_199Bitmasks
	dw Mon_19ABitmasks
	dw Mon_19BBitmasks
	dw Mon_19CBitmasks
	dw Mon_19DBitmasks
	dw Mon_19EBitmasks
	dw Mon_19FBitmasks
	dw Mon_190Bitmasks
	dw Mon_1A1Bitmasks
	dw Mon_1A2Bitmasks
	dw Mon_1A3Bitmasks
	dw Mon_1A4Bitmasks
	dw Mon_1A5Bitmasks
	dw Mon_1A6Bitmasks
	dw Mon_1A7Bitmasks
	dw Mon_1A8Bitmasks
	dw Mon_1A9Bitmasks
	dw Mon_1AABitmasks
	dw Mon_1ABBitmasks
	dw Mon_1ACBitmasks
	dw Mon_1ADBitmasks
	dw Mon_1AEBitmasks
	dw Mon_1AFBitmasks
	dw Mon_1B0Bitmasks
	dw Mon_1B1Bitmasks
	dw Mon_1B2Bitmasks
	dw Mon_1B3Bitmasks
	dw Mon_1B4Bitmasks
	dw Mon_1B5Bitmasks
	dw Mon_1B6Bitmasks
	dw Mon_1B7Bitmasks
	dw Mon_1B8Bitmasks
	dw Mon_1B9Bitmasks
	dw Mon_1BABitmasks
	dw Mon_1BBBitmasks
	dw Mon_1BCBitmasks
	dw Mon_1BDBitmasks
	dw Mon_1BEBitmasks
	dw Mon_1BFBitmasks
	dw Mon_1C0Bitmasks
	dw Mon_1C1Bitmasks
	dw Mon_1C2Bitmasks
	dw Mon_1C3Bitmasks
	dw Mon_1C4Bitmasks
	dw Mon_1C5Bitmasks
	dw Mon_1C6Bitmasks
	dw Mon_1C7Bitmasks
	dw Mon_1C8Bitmasks
	dw Mon_1C9Bitmasks
	dw Mon_1CABitmasks
	dw Mon_1CBBitmasks
	dw Mon_1CCBitmasks
	dw Mon_1CDBitmasks
	dw Mon_1CEBitmasks
	dw Mon_1CFBitmasks
	dw Mon_1D0Bitmasks
	dw Mon_1D1Bitmasks
	dw Mon_1D2Bitmasks
	dw Mon_1D3Bitmasks
	dw Mon_1D4Bitmasks
	dw Mon_1D5Bitmasks
	dw Mon_1D6Bitmasks
	dw Mon_1D7Bitmasks
	dw Mon_1D8Bitmasks
	dw Mon_1D9Bitmasks
	dw Mon_1DABitmasks
	dw Mon_1DBBitmasks
	dw Mon_1DCBitmasks
	dw Mon_1DDBitmasks
	dw Mon_1DEBitmasks
	dw Mon_1DFBitmasks
	dw Mon_1E0Bitmasks
	dw Mon_1E1Bitmasks
	dw Mon_1E2Bitmasks
	dw Mon_1E3Bitmasks
	dw Mon_1E4Bitmasks
	dw Mon_1E5Bitmasks
	dw Mon_1E6Bitmasks
	dw Mon_1E7Bitmasks
	dw Mon_1E8Bitmasks
	dw Mon_1E9Bitmasks
	dw Mon_1EABitmasks
	dw Mon_1EBBitmasks
	dw Mon_1ECBitmasks
	dw Mon_1EDBitmasks
	dw Mon_1EEBitmasks
	dw Mon_1EFBitmasks
	dw Mon_1F0Bitmasks
	dw Mon_1F1Bitmasks
	dw Mon_1F2Bitmasks
	dw Mon_1F3Bitmasks
	dw Mon_1F4Bitmasks
	dw Mon_1F5Bitmasks
	dw Mon_1F6Bitmasks
	dw Mon_1F7Bitmasks
	dw Mon_1F8Bitmasks
	dw Mon_1F9Bitmasks
	dw Mon_1FABitmasks
	dw Mon_1FBBitmasks
	dw Mon_1FCBitmasks
	dw Mon_1FDBitmasks
