AnimationIdlePointers:
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw CaterpieAnimationIdle
	dw MetapodAnimationIdle
	dw ButterfreeAnimationIdle
	dw WeedleAnimationIdle
	dw KakunaAnimationIdle
	dw BeedrillAnimationIdle
	dw PidgeyAnimationIdle
	dw PidgeottoAnimationIdle
	dw PidgeotAnimationIdle
	dw RattataAnimationIdle
	dw RaticateAnimationIdle
	dw SpearowAnimationIdle
	dw FearowAnimationIdle
	dw EkansAnimationIdle
	dw ArbokAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw JigglypuffAnimationIdle
	dw WigglytuffAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw OddishAnimationIdle
	dw GloomAnimationIdle
	dw VileplumeAnimationIdle
	dw ParasAnimationIdle
	dw ParasectAnimationIdle
	dw VenonatAnimationIdle
	dw VenomothAnimationIdle
	dw DiglettAnimationIdle
	dw DugtrioAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw PsyduckAnimationIdle
	dw GolduckAnimationIdle
	dw MankeyAnimationIdle
	dw PrimeapeAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw FarfetchDAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SeelAnimationIdle
	dw DewgongAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw ShellderAnimationIdle
	dw CloysterAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw KrabbyAnimationIdle
	dw KinglerAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw LickitungAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw ChanseyAnimationIdle
	dw TangelaAnimationIdle
	dw KangaskhanAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MrMimeAnimationIdle
	dw ScytherAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw PorygonAnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw SpinarakAnimationIdle
	dw AriadosAnimationIdle
	dw CrobatAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw PichuAnimationIdle
	dw CleffaAnimationIdle
	dw IgglybuffAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw BellossomAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SudowoodoAnimationIdle
	dw PolitoedAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw AipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw MurkrowAnimationIdle
	dw SlowkingAnimationIdle
	dw MisdreavusAnimationIdle
	dw UnownAnimationIdle
	dw WobbuffetAnimationIdle
	dw GirafarigAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw DunsparceAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw ScizorAnimationIdle
	dw ShuckleAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw CorsolaAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw DelibirdAnimationIdle
	dw MantineAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw Porygon2AnimationIdle
	dw StantlerAnimationIdle
	dw SmeargleAnimationIdle
	dw TyrogueAnimationIdle
	dw HitmontopAnimationIdle
	dw SmoochumAnimationIdle
	dw ElekidAnimationIdle
	dw MagbyAnimationIdle
	dw MiltankAnimationIdle
	dw BlisseyAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	dw CelebiAnimationIdle
	dw CelebiAnimationIdle
	dw 0, 0, 0
	dw YamaskAnimationIdle
	dw CofagrigusAnimationIdle
	dw FroakieAnimationIdle
	dw FrogadierAnimationIdle
	dw GreninjaAnimationIdle
	dw NincadaAnimationIdle
	dw NinjaskAnimationIdle
	dw ShedinjaAnimationIdle
	dw MegaVenusaurAnimationIdle
	dw Mon_10AAnimationIdle
	dw Mon_10BAnimationIdle
	dw Mon_10CAnimationIdle
	dw Mon_10DAnimationIdle
	dw Mon_10EAnimationIdle
	dw Mon_10FAnimationIdle
	dw Mon_110AnimationIdle
	dw Mon_111AnimationIdle
	dw Mon_112AnimationIdle
	dw Mon_113AnimationIdle
	dw Mon_114AnimationIdle
	dw Mon_115AnimationIdle
	dw Mon_116AnimationIdle
	dw Mon_117AnimationIdle
	dw Mon_118AnimationIdle
	dw Mon_119AnimationIdle
	dw Mon_11AAnimationIdle
	dw Mon_11BAnimationIdle
	dw Mon_11CAnimationIdle
	dw Mon_11DAnimationIdle
	dw Mon_11EAnimationIdle
	dw Mon_11FAnimationIdle
	dw Mon_120AnimationIdle
	dw Mon_121AnimationIdle
	dw Mon_122AnimationIdle
	dw Mon_123AnimationIdle
	dw Mon_124AnimationIdle
	dw Mon_125AnimationIdle
	dw Mon_126AnimationIdle
	dw Mon_127AnimationIdle
	dw Mon_128AnimationIdle
	dw Mon_129AnimationIdle
	dw Mon_12AAnimationIdle
	dw Mon_12BAnimationIdle
	dw Mon_12CAnimationIdle
	dw Mon_12DAnimationIdle
	dw Mon_12EAnimationIdle
	dw Mon_12FAnimationIdle
	dw Mon_130AnimationIdle
	dw Mon_131AnimationIdle
	dw Mon_132AnimationIdle
	dw Mon_133AnimationIdle
	dw Mon_134AnimationIdle
	dw Mon_135AnimationIdle
	dw Mon_136AnimationIdle
	dw Mon_137AnimationIdle
	dw Mon_138AnimationIdle
	dw Mon_139AnimationIdle
	dw Mon_13AAnimationIdle
	dw Mon_13BAnimationIdle
	dw Mon_13CAnimationIdle
	dw Mon_13DAnimationIdle
	dw Mon_13EAnimationIdle
	dw Mon_13FAnimationIdle
	dw Mon_140AnimationIdle
	dw Mon_141AnimationIdle
	dw Mon_142AnimationIdle
	dw Mon_143AnimationIdle
	dw Mon_144AnimationIdle
	dw Mon_145AnimationIdle
	dw Mon_146AnimationIdle
	dw Mon_147AnimationIdle
	dw Mon_148AnimationIdle
	dw Mon_149AnimationIdle
	dw Mon_14AAnimationIdle
	dw Mon_14BAnimationIdle
	dw Mon_14CAnimationIdle
	dw Mon_14DAnimationIdle
	dw Mon_14EAnimationIdle
	dw Mon_14FAnimationIdle
	dw Mon_150AnimationIdle
	dw Mon_151AnimationIdle
	dw Mon_152AnimationIdle
	dw Mon_153AnimationIdle
	dw Mon_154AnimationIdle
	dw Mon_155AnimationIdle
	dw Mon_156AnimationIdle
	dw Mon_157AnimationIdle
	dw Mon_158AnimationIdle
	dw Mon_159AnimationIdle
	dw Mon_15AAnimationIdle
	dw Mon_15BAnimationIdle
	dw Mon_15CAnimationIdle
	dw Mon_15DAnimationIdle
	dw Mon_15EAnimationIdle
	dw Mon_15FAnimationIdle
	dw Mon_160AnimationIdle
	dw Mon_161AnimationIdle
	dw Mon_162AnimationIdle
	dw Mon_163AnimationIdle
	dw Mon_164AnimationIdle
	dw Mon_165AnimationIdle
	dw Mon_166AnimationIdle
	dw Mon_167AnimationIdle
	dw Mon_168AnimationIdle
	dw Mon_169AnimationIdle
	dw Mon_16AAnimationIdle
	dw Mon_16BAnimationIdle
	dw Mon_16CAnimationIdle
	dw Mon_16DAnimationIdle
	dw Mon_16EAnimationIdle
	dw Mon_16FAnimationIdle
	dw Mon_170AnimationIdle
	dw Mon_171AnimationIdle
	dw Mon_172AnimationIdle
	dw Mon_173AnimationIdle
	dw Mon_174AnimationIdle
	dw Mon_175AnimationIdle
	dw Mon_176AnimationIdle
	dw Mon_177AnimationIdle
	dw Mon_178AnimationIdle
	dw Mon_179AnimationIdle
	dw Mon_17AAnimationIdle
	dw Mon_17BAnimationIdle
	dw Mon_17CAnimationIdle
	dw Mon_17DAnimationIdle
	dw Mon_17EAnimationIdle
	dw Mon_17FAnimationIdle
	dw Mon_180AnimationIdle
	dw Mon_181AnimationIdle
	dw Mon_182AnimationIdle
	dw Mon_183AnimationIdle
	dw Mon_184AnimationIdle
	dw Mon_185AnimationIdle
	dw Mon_186AnimationIdle
	dw Mon_187AnimationIdle
	dw Mon_188AnimationIdle
	dw Mon_189AnimationIdle
	dw Mon_18AAnimationIdle
	dw Mon_18BAnimationIdle
	dw Mon_18CAnimationIdle
	dw Mon_18DAnimationIdle
	dw Mon_18EAnimationIdle
	dw Mon_18FAnimationIdle
	dw Mon_190AnimationIdle
	dw Mon_191AnimationIdle
	dw Mon_192AnimationIdle
	dw Mon_193AnimationIdle
	dw Mon_194AnimationIdle
	dw Mon_195AnimationIdle
	dw Mon_196AnimationIdle
	dw Mon_197AnimationIdle
	dw Mon_198AnimationIdle
	dw Mon_199AnimationIdle
	dw Mon_19AAnimationIdle
	dw Mon_19BAnimationIdle
	dw Mon_19CAnimationIdle
	dw Mon_19DAnimationIdle
	dw Mon_19EAnimationIdle
	dw Mon_19FAnimationIdle
	dw Mon_1A0AnimationIdle
	dw Mon_1A1AnimationIdle
	dw Mon_1A2AnimationIdle
	dw Mon_1A3AnimationIdle
	dw Mon_1A4AnimationIdle
	dw Mon_1A5AnimationIdle
	dw Mon_1A6AnimationIdle
	dw Mon_1A7AnimationIdle
	dw Mon_1A8AnimationIdle
	dw Mon_1A9AnimationIdle
	dw Mon_1AAAnimationIdle
	dw Mon_1ABAnimationIdle
	dw Mon_1ACAnimationIdle
	dw Mon_1ADAnimationIdle
	dw Mon_1AEAnimationIdle
	dw Mon_1AFAnimationIdle
	dw Mon_1B0AnimationIdle
	dw Mon_1B1AnimationIdle
	dw Mon_1B2AnimationIdle
	dw Mon_1B3AnimationIdle
	dw Mon_1B4AnimationIdle
	dw Mon_1B5AnimationIdle
	dw Mon_1B6AnimationIdle
	dw Mon_1B7AnimationIdle
	dw Mon_1B8AnimationIdle
	dw Mon_1B9AnimationIdle
	dw Mon_1BAAnimationIdle
	dw Mon_1BBAnimationIdle
	dw Mon_1BCAnimationIdle
	dw Mon_1BDAnimationIdle
	dw Mon_1BEAnimationIdle
	dw Mon_1BFAnimationIdle
	dw Mon_1C0AnimationIdle
	dw Mon_1C1AnimationIdle
	dw Mon_1C2AnimationIdle
	dw Mon_1C3AnimationIdle
	dw Mon_1C4AnimationIdle
	dw Mon_1C5AnimationIdle
	dw Mon_1C6AnimationIdle
	dw Mon_1C7AnimationIdle
	dw Mon_1C8AnimationIdle
	dw Mon_1C9AnimationIdle
	dw Mon_1CAAnimationIdle
	dw Mon_1CBAnimationIdle
	dw Mon_1CCAnimationIdle
	dw Mon_1CDAnimationIdle
	dw Mon_1CEAnimationIdle
	dw Mon_1CFAnimationIdle
	dw Mon_1D0AnimationIdle
	dw Mon_1D1AnimationIdle
	dw Mon_1D2AnimationIdle
	dw Mon_1D3AnimationIdle
	dw Mon_1D4AnimationIdle
	dw Mon_1D5AnimationIdle
	dw Mon_1D6AnimationIdle
	dw Mon_1D7AnimationIdle
	dw Mon_1D8AnimationIdle
	dw Mon_1D9AnimationIdle
	dw Mon_1DAAnimationIdle
	dw Mon_1DBAnimationIdle
	dw Mon_1DCAnimationIdle
	dw Mon_1DDAnimationIdle
	dw Mon_1DEAnimationIdle
	dw Mon_1DFAnimationIdle
	dw Mon_1E0AnimationIdle
	dw Mon_1E1AnimationIdle
	dw Mon_1E2AnimationIdle
	dw Mon_1E3AnimationIdle
	dw Mon_1E4AnimationIdle
	dw Mon_1E5AnimationIdle
	dw Mon_1E6AnimationIdle
	dw Mon_1E7AnimationIdle
	dw Mon_1E8AnimationIdle
	dw Mon_1E9AnimationIdle
	dw Mon_1EAAnimationIdle
	dw Mon_1EBAnimationIdle
	dw Mon_1ECAnimationIdle
	dw Mon_1EDAnimationIdle
	dw Mon_1EEAnimationIdle
	dw Mon_1EFAnimationIdle
	dw Mon_1F0AnimationIdle
	dw Mon_1F1AnimationIdle
	dw Mon_1F2AnimationIdle
	dw Mon_1F3AnimationIdle
	dw Mon_1F4AnimationIdle
	dw Mon_1F5AnimationIdle
	dw Mon_1F6AnimationIdle
	dw Mon_1F7AnimationIdle
	dw Mon_1F8AnimationIdle
	dw Mon_1F9AnimationIdle
	dw Mon_1FAAnimationIdle
	dw Mon_1FBAnimationIdle
	dw Mon_1FCAnimationIdle
	dw Mon_1FDAnimationIdle
