INCLUDE "constants.asm"


; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in pokecrystal.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


SECTION "Pics 1", ROMX

HoOhFrontpic:        INCBIN "gfx/pokemon/ho_oh/front.animated.2bpp.lz"
MachampFrontpic:     INCBIN "gfx/pokemon/machamp/front.animated.2bpp.lz"
NinetalesFrontpic:   INCBIN "gfx/pokemon/ninetales/front.animated.2bpp.lz"
FeraligatrFrontpic:  INCBIN "gfx/pokemon/feraligatr/front.animated.2bpp.lz"
NidokingFrontpic:    INCBIN "gfx/pokemon/nidoking/front.animated.2bpp.lz"
RaikouFrontpic:      INCBIN "gfx/pokemon/raikou/front.animated.2bpp.lz"
LugiaFrontpic:       INCBIN "gfx/pokemon/lugia/front.animated.2bpp.lz"
ArticunoFrontpic:    INCBIN "gfx/pokemon/articuno/front.animated.2bpp.lz"



SECTION "Pics 2", ROMX

BlastoiseFrontpic:   INCBIN "gfx/pokemon/blastoise/front.animated.2bpp.lz"
RapidashFrontpic:    INCBIN "gfx/pokemon/rapidash/front.animated.2bpp.lz"
MeganiumFrontpic:    INCBIN "gfx/pokemon/meganium/front.animated.2bpp.lz"
NidoqueenFrontpic:   INCBIN "gfx/pokemon/nidoqueen/front.animated.2bpp.lz"
HitmonleeFrontpic:   INCBIN "gfx/pokemon/hitmonlee/front.animated.2bpp.lz"
ScizorFrontpic:      INCBIN "gfx/pokemon/scizor/front.animated.2bpp.lz"
BeedrillFrontpic:    INCBIN "gfx/pokemon/beedrill/front.animated.2bpp.lz"
ArcanineFrontpic:    INCBIN "gfx/pokemon/arcanine/front.animated.2bpp.lz"
TyranitarFrontpic:   INCBIN "gfx/pokemon/tyranitar/front.animated.2bpp.lz"
MoltresFrontpic:     INCBIN "gfx/pokemon/moltres/front.animated.2bpp.lz"
ZapdosFrontpic:      INCBIN "gfx/pokemon/zapdos/front.animated.2bpp.lz"
ArbokFrontpic:       INCBIN "gfx/pokemon/arbok/front.animated.2bpp.lz"
MewtwoFrontpic:      INCBIN "gfx/pokemon/mewtwo/front.animated.2bpp.lz"
FearowFrontpic:      INCBIN "gfx/pokemon/fearow/front.animated.2bpp.lz"
CharizardFrontpic:   INCBIN "gfx/pokemon/charizard/front.animated.2bpp.lz"
QuilavaFrontpic:     INCBIN "gfx/pokemon/quilava/front.animated.2bpp.lz"


SECTION "Pics 3", ROMX

SteelixFrontpic:     INCBIN "gfx/pokemon/steelix/front.animated.2bpp.lz"
AlakazamFrontpic:    INCBIN "gfx/pokemon/alakazam/front.animated.2bpp.lz"
GyaradosFrontpic:    INCBIN "gfx/pokemon/gyarados/front.animated.2bpp.lz"
KangaskhanFrontpic:  INCBIN "gfx/pokemon/kangaskhan/front.animated.2bpp.lz"
RhydonFrontpic:      INCBIN "gfx/pokemon/rhydon/front.animated.2bpp.lz"
GolduckFrontpic:     INCBIN "gfx/pokemon/golduck/front.animated.2bpp.lz"
RhyhornFrontpic:     INCBIN "gfx/pokemon/rhyhorn/front.animated.2bpp.lz"
PidgeotFrontpic:     INCBIN "gfx/pokemon/pidgeot/front.animated.2bpp.lz"
SlowbroFrontpic:     INCBIN "gfx/pokemon/slowbro/front.animated.2bpp.lz"
ButterfreeFrontpic:  INCBIN "gfx/pokemon/butterfree/front.animated.2bpp.lz"
WeezingFrontpic:     INCBIN "gfx/pokemon/weezing/front.animated.2bpp.lz"
CloysterFrontpic:    INCBIN "gfx/pokemon/cloyster/front.animated.2bpp.lz"
SkarmoryFrontpic:    INCBIN "gfx/pokemon/skarmory/front.animated.2bpp.lz"
DewgongFrontpic:     INCBIN "gfx/pokemon/dewgong/front.animated.2bpp.lz"
VictreebelFrontpic:  INCBIN "gfx/pokemon/victreebel/front.animated.2bpp.lz"
RaichuFrontpic:      INCBIN "gfx/pokemon/raichu/front.animated.2bpp.lz"
PrimeapeFrontpic:    INCBIN "gfx/pokemon/primeape/front.animated.2bpp.lz"
OmastarBackpic:      INCBIN "gfx/pokemon/omastar/back.2bpp.lz"


SECTION "Pics 4", ROMX

DodrioFrontpic:      INCBIN "gfx/pokemon/dodrio/front.animated.2bpp.lz"
SlowkingFrontpic:    INCBIN "gfx/pokemon/slowking/front.animated.2bpp.lz"
HitmontopFrontpic:   INCBIN "gfx/pokemon/hitmontop/front.animated.2bpp.lz"
OnixFrontpic:        INCBIN "gfx/pokemon/onix/front.animated.2bpp.lz"
BlisseyFrontpic:     INCBIN "gfx/pokemon/blissey/front.animated.2bpp.lz"
MachokeFrontpic:     INCBIN "gfx/pokemon/machoke/front.animated.2bpp.lz"
DragoniteFrontpic:   INCBIN "gfx/pokemon/dragonite/front.animated.2bpp.lz"
PoliwrathFrontpic:   INCBIN "gfx/pokemon/poliwrath/front.animated.2bpp.lz"
ScytherFrontpic:     INCBIN "gfx/pokemon/scyther/front.animated.2bpp.lz"
AerodactylFrontpic:  INCBIN "gfx/pokemon/aerodactyl/front.animated.2bpp.lz"
SeakingFrontpic:     INCBIN "gfx/pokemon/seaking/front.animated.2bpp.lz"
MukFrontpic:         INCBIN "gfx/pokemon/muk/front.animated.2bpp.lz"
CroconawFrontpic:    INCBIN "gfx/pokemon/croconaw/front.animated.2bpp.lz"
HypnoFrontpic:       INCBIN "gfx/pokemon/hypno/front.animated.2bpp.lz"
NidorinoFrontpic:    INCBIN "gfx/pokemon/nidorino/front.animated.2bpp.lz"
SandslashFrontpic:   INCBIN "gfx/pokemon/sandslash/front.animated.2bpp.lz"
JolteonFrontpic:     INCBIN "gfx/pokemon/jolteon/front.animated.2bpp.lz"
DonphanFrontpic:     INCBIN "gfx/pokemon/donphan/front.animated.2bpp.lz"
PinsirFrontpic:      INCBIN "gfx/pokemon/pinsir/front.animated.2bpp.lz"
UnownEFrontpic:      INCBIN "gfx/pokemon/unown_e/front.animated.2bpp.lz"


SECTION "Pics 5", ROMX

GolbatFrontpic:      INCBIN "gfx/pokemon/golbat/front.animated.2bpp.lz"
KinglerFrontpic:     INCBIN "gfx/pokemon/kingler/front.animated.2bpp.lz"
ExeggcuteFrontpic:   INCBIN "gfx/pokemon/exeggcute/front.animated.2bpp.lz"
MagcargoFrontpic:    INCBIN "gfx/pokemon/magcargo/front.animated.2bpp.lz"
PersianFrontpic:     INCBIN "gfx/pokemon/persian/front.animated.2bpp.lz"
StantlerFrontpic:    INCBIN "gfx/pokemon/stantler/front.animated.2bpp.lz"
RaticateFrontpic:    INCBIN "gfx/pokemon/raticate/front.animated.2bpp.lz"
VenomothFrontpic:    INCBIN "gfx/pokemon/venomoth/front.animated.2bpp.lz"
PolitoedFrontpic:    INCBIN "gfx/pokemon/politoed/front.animated.2bpp.lz"
ElectabuzzFrontpic:  INCBIN "gfx/pokemon/electabuzz/front.animated.2bpp.lz"
MantineFrontpic:     INCBIN "gfx/pokemon/mantine/front.animated.2bpp.lz"
LickitungFrontpic:   INCBIN "gfx/pokemon/lickitung/front.animated.2bpp.lz"
KingdraFrontpic:     INCBIN "gfx/pokemon/kingdra/front.animated.2bpp.lz"
CharmeleonFrontpic:  INCBIN "gfx/pokemon/charmeleon/front.animated.2bpp.lz"
KadabraFrontpic:     INCBIN "gfx/pokemon/kadabra/front.animated.2bpp.lz"
ExeggutorFrontpic:   INCBIN "gfx/pokemon/exeggutor/front.animated.2bpp.lz"
GastlyFrontpic:      INCBIN "gfx/pokemon/gastly/front.animated.2bpp.lz"
AzumarillFrontpic:   INCBIN "gfx/pokemon/azumarill/front.animated.2bpp.lz"
ParasectFrontpic:    INCBIN "gfx/pokemon/parasect/front.animated.2bpp.lz"
MrMimeFrontpic:      INCBIN "gfx/pokemon/mr__mime/front.animated.2bpp.lz"
HeracrossFrontpic:   INCBIN "gfx/pokemon/heracross/front.animated.2bpp.lz"


SECTION "Pics 6", ROMX

AriadosFrontpic:     INCBIN "gfx/pokemon/ariados/front.animated.2bpp.lz"
NoctowlFrontpic:     INCBIN "gfx/pokemon/noctowl/front.animated.2bpp.lz"
WartortleFrontpic:   INCBIN "gfx/pokemon/wartortle/front.animated.2bpp.lz"
LaprasFrontpic:      INCBIN "gfx/pokemon/lapras/front.animated.2bpp.lz"
GolemFrontpic:       INCBIN "gfx/pokemon/golem/front.animated.2bpp.lz"
PoliwhirlFrontpic:   INCBIN "gfx/pokemon/poliwhirl/front.animated.2bpp.lz"
UrsaringFrontpic:    INCBIN "gfx/pokemon/ursaring/front.animated.2bpp.lz"
HoundoomFrontpic:    INCBIN "gfx/pokemon/houndoom/front.animated.2bpp.lz"
KabutopsFrontpic:    INCBIN "gfx/pokemon/kabutops/front.animated.2bpp.lz"
AmpharosFrontpic:    INCBIN "gfx/pokemon/ampharos/front.animated.2bpp.lz"
NidorinaFrontpic:    INCBIN "gfx/pokemon/nidorina/front.animated.2bpp.lz"
FlareonFrontpic:     INCBIN "gfx/pokemon/flareon/front.animated.2bpp.lz"
FarfetchDFrontpic:   INCBIN "gfx/pokemon/farfetch_d/front.animated.2bpp.lz"
VileplumeFrontpic:   INCBIN "gfx/pokemon/vileplume/front.animated.2bpp.lz"
BayleefFrontpic:     INCBIN "gfx/pokemon/bayleef/front.animated.2bpp.lz"
MagmarFrontpic:      INCBIN "gfx/pokemon/magmar/front.animated.2bpp.lz"
TentacruelFrontpic:  INCBIN "gfx/pokemon/tentacruel/front.animated.2bpp.lz"
ElekidFrontpic:      INCBIN "gfx/pokemon/elekid/front.animated.2bpp.lz"
JumpluffFrontpic:    INCBIN "gfx/pokemon/jumpluff/front.animated.2bpp.lz"
MarowakFrontpic:     INCBIN "gfx/pokemon/marowak/front.animated.2bpp.lz"
VulpixFrontpic:      INCBIN "gfx/pokemon/vulpix/front.animated.2bpp.lz"
GligarFrontpic:      INCBIN "gfx/pokemon/gligar/front.animated.2bpp.lz"
DunsparceFrontpic:   INCBIN "gfx/pokemon/dunsparce/front.animated.2bpp.lz"


SECTION "Pics 7", ROMX

VaporeonFrontpic:    INCBIN "gfx/pokemon/vaporeon/front.animated.2bpp.lz"
GirafarigFrontpic:   INCBIN "gfx/pokemon/girafarig/front.animated.2bpp.lz"
DrowzeeFrontpic:     INCBIN "gfx/pokemon/drowzee/front.animated.2bpp.lz"
SneaselFrontpic:     INCBIN "gfx/pokemon/sneasel/front.animated.2bpp.lz"
BellossomFrontpic:   INCBIN "gfx/pokemon/bellossom/front.animated.2bpp.lz"
SnorlaxFrontpic:     INCBIN "gfx/pokemon/snorlax/front.animated.2bpp.lz"
WigglytuffFrontpic:  INCBIN "gfx/pokemon/wigglytuff/front.animated.2bpp.lz"
YanmaFrontpic:       INCBIN "gfx/pokemon/yanma/front.animated.2bpp.lz"
SmeargleFrontpic:    INCBIN "gfx/pokemon/smeargle/front.animated.2bpp.lz"
ClefableFrontpic:    INCBIN "gfx/pokemon/clefable/front.animated.2bpp.lz"
PonytaFrontpic:      INCBIN "gfx/pokemon/ponyta/front.animated.2bpp.lz"
MurkrowFrontpic:     INCBIN "gfx/pokemon/murkrow/front.animated.2bpp.lz"
GravelerFrontpic:    INCBIN "gfx/pokemon/graveler/front.animated.2bpp.lz"
StarmieFrontpic:     INCBIN "gfx/pokemon/starmie/front.animated.2bpp.lz"
PidgeottoFrontpic:   INCBIN "gfx/pokemon/pidgeotto/front.animated.2bpp.lz"
LedybaFrontpic:      INCBIN "gfx/pokemon/ledyba/front.animated.2bpp.lz"
GengarFrontpic:      INCBIN "gfx/pokemon/gengar/front.animated.2bpp.lz"
OmastarFrontpic:     INCBIN "gfx/pokemon/omastar/front.animated.2bpp.lz"
PiloswineFrontpic:   INCBIN "gfx/pokemon/piloswine/front.animated.2bpp.lz"
DugtrioFrontpic:     INCBIN "gfx/pokemon/dugtrio/front.animated.2bpp.lz"
MagnetonFrontpic:    INCBIN "gfx/pokemon/magneton/front.animated.2bpp.lz"
DragonairFrontpic:   INCBIN "gfx/pokemon/dragonair/front.animated.2bpp.lz"
ForretressFrontpic:  INCBIN "gfx/pokemon/forretress/front.animated.2bpp.lz"
TogeticFrontpic:     INCBIN "gfx/pokemon/togetic/front.animated.2bpp.lz"
KangaskhanBackpic:   INCBIN "gfx/pokemon/kangaskhan/back.2bpp.lz"


SECTION "Pics 8", ROMX

SeelFrontpic:        INCBIN "gfx/pokemon/seel/front.animated.2bpp.lz"
CrobatFrontpic:      INCBIN "gfx/pokemon/crobat/front.animated.2bpp.lz"
ChanseyFrontpic:     INCBIN "gfx/pokemon/chansey/front.animated.2bpp.lz"
TangelaFrontpic:     INCBIN "gfx/pokemon/tangela/front.animated.2bpp.lz"
SnubbullFrontpic:    INCBIN "gfx/pokemon/snubbull/front.animated.2bpp.lz"
GranbullFrontpic:    INCBIN "gfx/pokemon/granbull/front.animated.2bpp.lz"
MiltankFrontpic:     INCBIN "gfx/pokemon/miltank/front.animated.2bpp.lz"
HaunterFrontpic:     INCBIN "gfx/pokemon/haunter/front.animated.2bpp.lz"
SunfloraFrontpic:    INCBIN "gfx/pokemon/sunflora/front.animated.2bpp.lz"
UmbreonFrontpic:     INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
ChikoritaFrontpic:   INCBIN "gfx/pokemon/chikorita/front.animated.2bpp.lz"
GoldeenFrontpic:     INCBIN "gfx/pokemon/goldeen/front.animated.2bpp.lz"
EspeonFrontpic:      INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
XatuFrontpic:        INCBIN "gfx/pokemon/xatu/front.animated.2bpp.lz"
MewFrontpic:         INCBIN "gfx/pokemon/mew/front.animated.2bpp.lz"
OctilleryFrontpic:   INCBIN "gfx/pokemon/octillery/front.animated.2bpp.lz"
JynxFrontpic:        INCBIN "gfx/pokemon/jynx/front.animated.2bpp.lz"
WobbuffetFrontpic:   INCBIN "gfx/pokemon/wobbuffet/front.animated.2bpp.lz"
DelibirdFrontpic:    INCBIN "gfx/pokemon/delibird/front.animated.2bpp.lz"
LedianFrontpic:      INCBIN "gfx/pokemon/ledian/front.animated.2bpp.lz"
GloomFrontpic:       INCBIN "gfx/pokemon/gloom/front.animated.2bpp.lz"
FlaaffyFrontpic:     INCBIN "gfx/pokemon/flaaffy/front.animated.2bpp.lz"
IvysaurFrontpic:     INCBIN "gfx/pokemon/ivysaur/front.animated.2bpp.lz"
FurretFrontpic:      INCBIN "gfx/pokemon/furret/front.animated.2bpp.lz"
CyndaquilFrontpic:   INCBIN "gfx/pokemon/cyndaquil/front.animated.2bpp.lz"
HitmonchanFrontpic:  INCBIN "gfx/pokemon/hitmonchan/front.animated.2bpp.lz"
QuagsireFrontpic:    INCBIN "gfx/pokemon/quagsire/front.animated.2bpp.lz"


SECTION "Pics 9", ROMX

EkansFrontpic:       INCBIN "gfx/pokemon/ekans/front.animated.2bpp.lz"
SudowoodoFrontpic:   INCBIN "gfx/pokemon/sudowoodo/front.animated.2bpp.lz"
PikachuFrontpic:     INCBIN "gfx/pokemon/pikachu/front.animated.2bpp.lz"
SeadraFrontpic:      INCBIN "gfx/pokemon/seadra/front.animated.2bpp.lz"
MagbyFrontpic:       INCBIN "gfx/pokemon/magby/front.animated.2bpp.lz"
WeepinbellFrontpic:  INCBIN "gfx/pokemon/weepinbell/front.animated.2bpp.lz"
TotodileFrontpic:    INCBIN "gfx/pokemon/totodile/front.animated.2bpp.lz"
CorsolaFrontpic:     INCBIN "gfx/pokemon/corsola/front.animated.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/firebreather.2bpp.lz"
MachopFrontpic:      INCBIN "gfx/pokemon/machop/front.animated.2bpp.lz"
ChinchouFrontpic:    INCBIN "gfx/pokemon/chinchou/front.animated.2bpp.lz"
RattataFrontpic:     INCBIN "gfx/pokemon/rattata/front.animated.2bpp.lz"
ChampionPic:         INCBIN "gfx/trainers/champion.2bpp.lz"
SpearowFrontpic:     INCBIN "gfx/pokemon/spearow/front.animated.2bpp.lz"
MagikarpFrontpic:    INCBIN "gfx/pokemon/magikarp/front.animated.2bpp.lz"
CharmanderFrontpic:  INCBIN "gfx/pokemon/charmander/front.animated.2bpp.lz"
CuboneFrontpic:      INCBIN "gfx/pokemon/cubone/front.animated.2bpp.lz"
BlackbeltTPic:       INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
BikerPic:            INCBIN "gfx/trainers/biker.2bpp.lz"
NidoranMFrontpic:    INCBIN "gfx/pokemon/nidoran_m/front.animated.2bpp.lz"
PorygonFrontpic:     INCBIN "gfx/pokemon/porygon/front.animated.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/bruno.2bpp.lz"
GrimerFrontpic:      INCBIN "gfx/pokemon/grimer/front.animated.2bpp.lz"
StaryuFrontpic:      INCBIN "gfx/pokemon/staryu/front.animated.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/hiker.2bpp.lz"
MeowthFrontpic:      INCBIN "gfx/pokemon/meowth/front.animated.2bpp.lz"
Porygon2Frontpic:    INCBIN "gfx/pokemon/porygon2/front.animated.2bpp.lz"
SandshrewFrontpic:   INCBIN "gfx/pokemon/sandshrew/front.animated.2bpp.lz"
NidoranFFrontpic:    INCBIN "gfx/pokemon/nidoran_f/front.animated.2bpp.lz"
PidgeyFrontpic:      INCBIN "gfx/pokemon/pidgey/front.animated.2bpp.lz"
ParasectBackpic:     INCBIN "gfx/pokemon/parasect/back.2bpp.lz"


SECTION "Pics 10", ROMX

MisdreavusFrontpic:  INCBIN "gfx/pokemon/misdreavus/front.animated.2bpp.lz"
HoundourFrontpic:    INCBIN "gfx/pokemon/houndour/front.animated.2bpp.lz"
MankeyFrontpic:      INCBIN "gfx/pokemon/mankey/front.animated.2bpp.lz"
CelebiFrontpic:      INCBIN "gfx/pokemon/celebi/front.animated.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/medium.2bpp.lz"
PinecoFrontpic:      INCBIN "gfx/pokemon/pineco/front.animated.2bpp.lz"
KrabbyFrontpic:      INCBIN "gfx/pokemon/krabby/front.animated.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/fisher.2bpp.lz"
JigglypuffFrontpic:  INCBIN "gfx/pokemon/jigglypuff/front.animated.2bpp.lz"
ParasFrontpic:       INCBIN "gfx/pokemon/paras/front.animated.2bpp.lz"
NidokingBackpic:     INCBIN "gfx/pokemon/nidoking/back.2bpp.lz"
PokefanmPic:         INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
BoarderPic:          INCBIN "gfx/trainers/boarder.2bpp.lz"
PsyduckFrontpic:     INCBIN "gfx/pokemon/psyduck/front.animated.2bpp.lz"
SquirtleFrontpic:    INCBIN "gfx/pokemon/squirtle/front.animated.2bpp.lz"
MachampBackpic:      INCBIN "gfx/pokemon/machamp/back.2bpp.lz"
KoffingFrontpic:     INCBIN "gfx/pokemon/koffing/front.animated.2bpp.lz"
VenonatFrontpic:     INCBIN "gfx/pokemon/venonat/front.animated.2bpp.lz"
ExeggutorBackpic:    INCBIN "gfx/pokemon/exeggutor/back.2bpp.lz"
LanturnFrontpic:     INCBIN "gfx/pokemon/lanturn/front.animated.2bpp.lz"
TyrogueFrontpic:     INCBIN "gfx/pokemon/tyrogue/front.animated.2bpp.lz"
SkiploomFrontpic:    INCBIN "gfx/pokemon/skiploom/front.animated.2bpp.lz"
MareepFrontpic:      INCBIN "gfx/pokemon/mareep/front.animated.2bpp.lz"
ChuckPic:            INCBIN "gfx/trainers/chuck.2bpp.lz"
EeveeFrontpic:       INCBIN "gfx/pokemon/eevee/front.animated.2bpp.lz"
ButterfreeBackpic:   INCBIN "gfx/pokemon/butterfree/back.2bpp.lz"
ZubatFrontpic:       INCBIN "gfx/pokemon/zubat/front.animated.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
AlakazamBackpic:     INCBIN "gfx/pokemon/alakazam/back.2bpp.lz"
AipomFrontpic:       INCBIN "gfx/pokemon/aipom/front.animated.2bpp.lz"
AbraFrontpic:        INCBIN "gfx/pokemon/abra/front.animated.2bpp.lz"
HitmontopBackpic:    INCBIN "gfx/pokemon/hitmontop/back.2bpp.lz"
CloysterBackpic:     INCBIN "gfx/pokemon/cloyster/back.2bpp.lz"
HoothootFrontpic:    INCBIN "gfx/pokemon/hoothoot/front.animated.2bpp.lz"
UnownFBackpic:       INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"


SECTION "Pics 11", ROMX

DodrioBackpic:       INCBIN "gfx/pokemon/dodrio/back.2bpp.lz"
ClefairyFrontpic:    INCBIN "gfx/pokemon/clefairy/front.animated.2bpp.lz"
SlugmaFrontpic:      INCBIN "gfx/pokemon/slugma/front.animated.2bpp.lz"
GrowlitheFrontpic:   INCBIN "gfx/pokemon/growlithe/front.animated.2bpp.lz"
SlowpokeFrontpic:    INCBIN "gfx/pokemon/slowpoke/front.animated.2bpp.lz"
SmoochumFrontpic:    INCBIN "gfx/pokemon/smoochum/front.animated.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/juggler.2bpp.lz"
MarillFrontpic:      INCBIN "gfx/pokemon/marill/front.animated.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/guitarist.2bpp.lz"
PokefanfPic:         INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
VenomothBackpic:     INCBIN "gfx/pokemon/venomoth/back.2bpp.lz"
ClairPic:            INCBIN "gfx/trainers/clair.2bpp.lz"
PokemaniacPic:       INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
OmanyteFrontpic:     INCBIN "gfx/pokemon/omanyte/front.animated.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/skier.2bpp.lz"
PupitarFrontpic:     INCBIN "gfx/pokemon/pupitar/front.animated.2bpp.lz"
BellsproutFrontpic:  INCBIN "gfx/pokemon/bellsprout/front.animated.2bpp.lz"
ShellderFrontpic:    INCBIN "gfx/pokemon/shellder/front.animated.2bpp.lz"
TentacoolFrontpic:   INCBIN "gfx/pokemon/tentacool/front.animated.2bpp.lz"
CleffaFrontpic:      INCBIN "gfx/pokemon/cleffa/front.animated.2bpp.lz"
GyaradosBackpic:     INCBIN "gfx/pokemon/gyarados/back.2bpp.lz"
NinetalesBackpic:    INCBIN "gfx/pokemon/ninetales/back.2bpp.lz"
YanmaBackpic:        INCBIN "gfx/pokemon/yanma/back.2bpp.lz"
PinsirBackpic:       INCBIN "gfx/pokemon/pinsir/back.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/lass.2bpp.lz"
ClefableBackpic:     INCBIN "gfx/pokemon/clefable/back.2bpp.lz"
DoduoFrontpic:       INCBIN "gfx/pokemon/doduo/front.animated.2bpp.lz"
FeraligatrBackpic:   INCBIN "gfx/pokemon/feraligatr/back.2bpp.lz"
DratiniFrontpic:     INCBIN "gfx/pokemon/dratini/front.animated.2bpp.lz"
MagnetonBackpic:     INCBIN "gfx/pokemon/magneton/back.2bpp.lz"
QwilfishFrontpic:    INCBIN "gfx/pokemon/qwilfish/front.animated.2bpp.lz"
SuicuneBackpic:      INCBIN "gfx/pokemon/suicune/back.2bpp.lz"
SlowkingBackpic:     INCBIN "gfx/pokemon/slowking/back.2bpp.lz"
ElekidBackpic:       INCBIN "gfx/pokemon/elekid/back.2bpp.lz"
CelebiBackpic:       INCBIN "gfx/pokemon/celebi/back.2bpp.lz"
KrabbyBackpic:       INCBIN "gfx/pokemon/krabby/back.2bpp.lz"
BugCatcherPic:       INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
SnorlaxBackpic:      INCBIN "gfx/pokemon/snorlax/back.2bpp.lz"


SECTION "Pics 12", ROMX

VenusaurBackpic:     INCBIN "gfx/pokemon/venusaur/back.2bpp.lz"
MoltresBackpic:      INCBIN "gfx/pokemon/moltres/back.2bpp.lz"
SunfloraBackpic:     INCBIN "gfx/pokemon/sunflora/back.2bpp.lz"
PhanpyFrontpic:      INCBIN "gfx/pokemon/phanpy/front.animated.2bpp.lz"
RhydonBackpic:       INCBIN "gfx/pokemon/rhydon/back.2bpp.lz"
LarvitarFrontpic:    INCBIN "gfx/pokemon/larvitar/front.animated.2bpp.lz"
TyranitarBackpic:    INCBIN "gfx/pokemon/tyranitar/back.2bpp.lz"
SandslashBackpic:    INCBIN "gfx/pokemon/sandslash/back.2bpp.lz"
SeadraBackpic:       INCBIN "gfx/pokemon/seadra/back.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/twins.2bpp.lz"
FarfetchDBackpic:    INCBIN "gfx/pokemon/farfetch_d/back.2bpp.lz"
NidoranMBackpic:     INCBIN "gfx/pokemon/nidoran_m/back.2bpp.lz"
LedybaBackpic:       INCBIN "gfx/pokemon/ledyba/back.2bpp.lz"
CyndaquilBackpic:    INCBIN "gfx/pokemon/cyndaquil/back.2bpp.lz"
BayleefBackpic:      INCBIN "gfx/pokemon/bayleef/back.2bpp.lz"
OddishFrontpic:      INCBIN "gfx/pokemon/oddish/front.animated.2bpp.lz"
RapidashBackpic:     INCBIN "gfx/pokemon/rapidash/back.2bpp.lz"
DoduoBackpic:        INCBIN "gfx/pokemon/doduo/back.2bpp.lz"
HoppipFrontpic:      INCBIN "gfx/pokemon/hoppip/front.animated.2bpp.lz"
MankeyBackpic:       INCBIN "gfx/pokemon/mankey/back.2bpp.lz"
MagmarBackpic:       INCBIN "gfx/pokemon/magmar/back.2bpp.lz"
HypnoBackpic:        INCBIN "gfx/pokemon/hypno/back.2bpp.lz"
QuilavaBackpic:      INCBIN "gfx/pokemon/quilava/back.2bpp.lz"
CroconawBackpic:     INCBIN "gfx/pokemon/croconaw/back.2bpp.lz"
SandshrewBackpic:    INCBIN "gfx/pokemon/sandshrew/back.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/sailor.2bpp.lz"
BeautyPic:           INCBIN "gfx/trainers/beauty.2bpp.lz"
ShellderBackpic:     INCBIN "gfx/pokemon/shellder/back.2bpp.lz"
ZubatBackpic:        INCBIN "gfx/pokemon/zubat/back.2bpp.lz"
TeddiursaFrontpic:   INCBIN "gfx/pokemon/teddiursa/front.animated.2bpp.lz"
CuboneBackpic:       INCBIN "gfx/pokemon/cubone/back.2bpp.lz"
GruntmPic:           INCBIN "gfx/trainers/grunt_m.2bpp.lz"
GloomBackpic:        INCBIN "gfx/pokemon/gloom/back.2bpp.lz"
MagcargoBackpic:     INCBIN "gfx/pokemon/magcargo/back.2bpp.lz"
KabutopsBackpic:     INCBIN "gfx/pokemon/kabutops/back.2bpp.lz"
BeedrillBackpic:     INCBIN "gfx/pokemon/beedrill/back.2bpp.lz"
ArcanineBackpic:     INCBIN "gfx/pokemon/arcanine/back.2bpp.lz"
FlareonBackpic:      INCBIN "gfx/pokemon/flareon/back.2bpp.lz"
GoldeenBackpic:      INCBIN "gfx/pokemon/goldeen/back.2bpp.lz"
BulbasaurFrontpic:   INCBIN "gfx/pokemon/bulbasaur/front.animated.2bpp.lz"
StarmieBackpic:      INCBIN "gfx/pokemon/starmie/back.2bpp.lz"


SECTION "Pics 13", ROMX

OmanyteBackpic:      INCBIN "gfx/pokemon/omanyte/back.2bpp.lz"
PidgeyBackpic:       INCBIN "gfx/pokemon/pidgey/back.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
QwilfishBackpic:     INCBIN "gfx/pokemon/qwilfish/back.2bpp.lz"
GligarBackpic:       INCBIN "gfx/pokemon/gligar/back.2bpp.lz"
TyphlosionBackpic:   INCBIN "gfx/pokemon/typhlosion/back.2bpp.lz"
CharmeleonBackpic:   INCBIN "gfx/pokemon/charmeleon/back.2bpp.lz"
NidoqueenBackpic:    INCBIN "gfx/pokemon/nidoqueen/back.2bpp.lz"
PichuFrontpic:       INCBIN "gfx/pokemon/pichu/front.animated.2bpp.lz"
ElectabuzzBackpic:   INCBIN "gfx/pokemon/electabuzz/back.2bpp.lz"
LedianBackpic:       INCBIN "gfx/pokemon/ledian/back.2bpp.lz"
PupitarBackpic:      INCBIN "gfx/pokemon/pupitar/back.2bpp.lz"
HeracrossBackpic:    INCBIN "gfx/pokemon/heracross/back.2bpp.lz"
UnownDFrontpic:      INCBIN "gfx/pokemon/unown_d/front.animated.2bpp.lz"
MiltankBackpic:      INCBIN "gfx/pokemon/miltank/back.2bpp.lz"
SteelixBackpic:      INCBIN "gfx/pokemon/steelix/back.2bpp.lz"
PersianBackpic:      INCBIN "gfx/pokemon/persian/back.2bpp.lz"
LtSurgePic:          INCBIN "gfx/trainers/lt_surge.2bpp.lz"
TeacherPic:          INCBIN "gfx/trainers/teacher.2bpp.lz"
EggPic:              INCBIN "gfx/pokemon/egg/front.animated.2bpp.lz"
EeveeBackpic:        INCBIN "gfx/pokemon/eevee/back.2bpp.lz"
ShuckleFrontpic:     INCBIN "gfx/pokemon/shuckle/front.animated.2bpp.lz"
PonytaBackpic:       INCBIN "gfx/pokemon/ponyta/back.2bpp.lz"
RemoraidFrontpic:    INCBIN "gfx/pokemon/remoraid/front.animated.2bpp.lz"
PoliwagFrontpic:     INCBIN "gfx/pokemon/poliwag/front.animated.2bpp.lz"
OnixBackpic:         INCBIN "gfx/pokemon/onix/back.2bpp.lz"
KoffingBackpic:      INCBIN "gfx/pokemon/koffing/back.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
FalknerPic:          INCBIN "gfx/trainers/falkner.2bpp.lz"
KarenPic:            INCBIN "gfx/trainers/karen.2bpp.lz"
NidorinaBackpic:     INCBIN "gfx/pokemon/nidorina/back.2bpp.lz"
TentacruelBackpic:   INCBIN "gfx/pokemon/tentacruel/back.2bpp.lz"
GrowlitheBackpic:    INCBIN "gfx/pokemon/growlithe/back.2bpp.lz"
KogaPic:             INCBIN "gfx/trainers/koga.2bpp.lz"
MachokeBackpic:      INCBIN "gfx/pokemon/machoke/back.2bpp.lz"
RaichuBackpic:       INCBIN "gfx/pokemon/raichu/back.2bpp.lz"
PoliwrathBackpic:    INCBIN "gfx/pokemon/poliwrath/back.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
SunkernFrontpic:     INCBIN "gfx/pokemon/sunkern/front.animated.2bpp.lz"
NidorinoBackpic:     INCBIN "gfx/pokemon/nidorino/back.2bpp.lz"
MysticalmanPic:      INCBIN "gfx/trainers/mysticalman.2bpp.lz"
CooltrainerfPic:     INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
ElectrodeFrontpic:   INCBIN "gfx/pokemon/electrode/front.animated.2bpp.lz"


SECTION "Pics 14", ROMX

SudowoodoBackpic:    INCBIN "gfx/pokemon/sudowoodo/back.2bpp.lz"
FlaaffyBackpic:      INCBIN "gfx/pokemon/flaaffy/back.2bpp.lz"
SentretFrontpic:     INCBIN "gfx/pokemon/sentret/front.animated.2bpp.lz"
TogeticBackpic:      INCBIN "gfx/pokemon/togetic/back.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/bugsy.2bpp.lz"
MarowakBackpic:      INCBIN "gfx/pokemon/marowak/back.2bpp.lz"
GeodudeBackpic:      INCBIN "gfx/pokemon/geodude/back.2bpp.lz"
ScytherBackpic:      INCBIN "gfx/pokemon/scyther/back.2bpp.lz"
VileplumeBackpic:    INCBIN "gfx/pokemon/vileplume/back.2bpp.lz"
HitmonchanBackpic:   INCBIN "gfx/pokemon/hitmonchan/back.2bpp.lz"
JumpluffBackpic:     INCBIN "gfx/pokemon/jumpluff/back.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
BlastoiseBackpic:    INCBIN "gfx/pokemon/blastoise/back.2bpp.lz"
MisdreavusBackpic:   INCBIN "gfx/pokemon/misdreavus/back.2bpp.lz"
TyrogueBackpic:      INCBIN "gfx/pokemon/tyrogue/back.2bpp.lz"
GeodudeFrontpic:     INCBIN "gfx/pokemon/geodude/front.animated.2bpp.lz"
ScizorBackpic:       INCBIN "gfx/pokemon/scizor/back.2bpp.lz"
GirafarigBackpic:    INCBIN "gfx/pokemon/girafarig/back.2bpp.lz"
StantlerBackpic:     INCBIN "gfx/pokemon/stantler/back.2bpp.lz"
SmeargleBackpic:     INCBIN "gfx/pokemon/smeargle/back.2bpp.lz"
CharizardBackpic:    INCBIN "gfx/pokemon/charizard/back.2bpp.lz"
KadabraBackpic:      INCBIN "gfx/pokemon/kadabra/back.2bpp.lz"
PrimeapeBackpic:     INCBIN "gfx/pokemon/primeape/back.2bpp.lz"
FurretBackpic:       INCBIN "gfx/pokemon/furret/back.2bpp.lz"
WartortleBackpic:    INCBIN "gfx/pokemon/wartortle/back.2bpp.lz"
ExeggcuteBackpic:    INCBIN "gfx/pokemon/exeggcute/back.2bpp.lz"
IgglybuffFrontpic:   INCBIN "gfx/pokemon/igglybuff/front.animated.2bpp.lz"
RaticateBackpic:     INCBIN "gfx/pokemon/raticate/back.2bpp.lz"
VulpixBackpic:       INCBIN "gfx/pokemon/vulpix/back.2bpp.lz"
EkansBackpic:        INCBIN "gfx/pokemon/ekans/back.2bpp.lz"
SeakingBackpic:      INCBIN "gfx/pokemon/seaking/back.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/burglar.2bpp.lz"
PsyduckBackpic:      INCBIN "gfx/pokemon/psyduck/back.2bpp.lz"
PikachuBackpic:      INCBIN "gfx/pokemon/pikachu/back.2bpp.lz"
KabutoFrontpic:      INCBIN "gfx/pokemon/kabuto/front.animated.2bpp.lz"
MareepBackpic:       INCBIN "gfx/pokemon/mareep/back.2bpp.lz"
RemoraidBackpic:     INCBIN "gfx/pokemon/remoraid/back.2bpp.lz"
DittoFrontpic:       INCBIN "gfx/pokemon/ditto/front.animated.2bpp.lz"
KingdraBackpic:      INCBIN "gfx/pokemon/kingdra/back.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/camper.2bpp.lz"
WooperFrontpic:      INCBIN "gfx/pokemon/wooper/front.animated.2bpp.lz"
ClefairyBackpic:     INCBIN "gfx/pokemon/clefairy/back.2bpp.lz"
VenonatBackpic:      INCBIN "gfx/pokemon/venonat/back.2bpp.lz"
BellossomBackpic:    INCBIN "gfx/pokemon/bellossom/back.2bpp.lz"
Rival1Pic:           INCBIN "gfx/trainers/rival1.2bpp.lz"
SwinubBackpic:       INCBIN "gfx/pokemon/swinub/back.2bpp.lz"


SECTION "Pics 15", ROMX

MewtwoBackpic:       INCBIN "gfx/pokemon/mewtwo/back.2bpp.lz"
PokemonProfPic:      INCBIN "gfx/trainers/oak.2bpp.lz"
CalPic:              INCBIN "gfx/trainers/cal.2bpp.lz"
SwimmerfPic:         INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
DiglettFrontpic:     INCBIN "gfx/pokemon/diglett/front.animated.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/officer.2bpp.lz"
MukBackpic:          INCBIN "gfx/pokemon/muk/back.2bpp.lz"
DelibirdBackpic:     INCBIN "gfx/pokemon/delibird/back.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/sabrina.2bpp.lz"
MagikarpBackpic:     INCBIN "gfx/pokemon/magikarp/back.2bpp.lz"
AriadosBackpic:      INCBIN "gfx/pokemon/ariados/back.2bpp.lz"
SneaselBackpic:      INCBIN "gfx/pokemon/sneasel/back.2bpp.lz"
UmbreonBackpic:      INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
MurkrowBackpic:      INCBIN "gfx/pokemon/murkrow/back.2bpp.lz"
IvysaurBackpic:      INCBIN "gfx/pokemon/ivysaur/back.2bpp.lz"
SlowbroBackpic:      INCBIN "gfx/pokemon/slowbro/back.2bpp.lz"
PsychicTPic:         INCBIN "gfx/trainers/psychic_t.2bpp.lz"
GolduckBackpic:      INCBIN "gfx/pokemon/golduck/back.2bpp.lz"
WeezingBackpic:      INCBIN "gfx/pokemon/weezing/back.2bpp.lz"
EnteiBackpic:        INCBIN "gfx/pokemon/entei/back.2bpp.lz"
GruntfPic:           INCBIN "gfx/trainers/grunt_f.2bpp.lz"
HorseaFrontpic:      INCBIN "gfx/pokemon/horsea/front.animated.2bpp.lz"
PidgeotBackpic:      INCBIN "gfx/pokemon/pidgeot/back.2bpp.lz"
HoOhBackpic:         INCBIN "gfx/pokemon/ho_oh/back.2bpp.lz"
PoliwhirlBackpic:    INCBIN "gfx/pokemon/poliwhirl/back.2bpp.lz"
MewBackpic:          INCBIN "gfx/pokemon/mew/back.2bpp.lz"
MachopBackpic:       INCBIN "gfx/pokemon/machop/back.2bpp.lz"
AbraBackpic:         INCBIN "gfx/pokemon/abra/back.2bpp.lz"
AerodactylBackpic:   INCBIN "gfx/pokemon/aerodactyl/back.2bpp.lz"
KakunaFrontpic:      INCBIN "gfx/pokemon/kakuna/front.animated.2bpp.lz"
DugtrioBackpic:      INCBIN "gfx/pokemon/dugtrio/back.2bpp.lz"
WeepinbellBackpic:   INCBIN "gfx/pokemon/weepinbell/back.2bpp.lz"
NidoranFBackpic:     INCBIN "gfx/pokemon/nidoran_f/back.2bpp.lz"
GravelerBackpic:     INCBIN "gfx/pokemon/graveler/back.2bpp.lz"
AipomBackpic:        INCBIN "gfx/pokemon/aipom/back.2bpp.lz"
EspeonBackpic:       INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
WeedleFrontpic:      INCBIN "gfx/pokemon/weedle/front.animated.2bpp.lz"
TotodileBackpic:     INCBIN "gfx/pokemon/totodile/back.2bpp.lz"
SnubbullBackpic:     INCBIN "gfx/pokemon/snubbull/back.2bpp.lz"
KinglerBackpic:      INCBIN "gfx/pokemon/kingler/back.2bpp.lz"
GengarBackpic:       INCBIN "gfx/pokemon/gengar/back.2bpp.lz"
RattataBackpic:      INCBIN "gfx/pokemon/rattata/back.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
WillPic:             INCBIN "gfx/trainers/will.2bpp.lz"
SchoolboyPic:        INCBIN "gfx/trainers/schoolboy.2bpp.lz"
MagnemiteFrontpic:   INCBIN "gfx/pokemon/magnemite/front.animated.2bpp.lz"
ErikaPic:            INCBIN "gfx/trainers/erika.2bpp.lz"
JaninePic:           INCBIN "gfx/trainers/janine.2bpp.lz"
MagnemiteBackpic:    INCBIN "gfx/pokemon/magnemite/back.2bpp.lz"


SECTION "Pics 16", ROMX

HoothootBackpic:     INCBIN "gfx/pokemon/hoothoot/back.2bpp.lz"
NoctowlBackpic:      INCBIN "gfx/pokemon/noctowl/back.2bpp.lz"
MortyPic:            INCBIN "gfx/trainers/morty.2bpp.lz"
SlugmaBackpic:       INCBIN "gfx/pokemon/slugma/back.2bpp.lz"
KabutoBackpic:       INCBIN "gfx/pokemon/kabuto/back.2bpp.lz"
VictreebelBackpic:   INCBIN "gfx/pokemon/victreebel/back.2bpp.lz"
MeowthBackpic:       INCBIN "gfx/pokemon/meowth/back.2bpp.lz"
MeganiumBackpic:     INCBIN "gfx/pokemon/meganium/back.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/picnicker.2bpp.lz"
LickitungBackpic:    INCBIN "gfx/pokemon/lickitung/back.2bpp.lz"
TogepiFrontpic:      INCBIN "gfx/pokemon/togepi/front.animated.2bpp.lz"
SuperNerdPic:        INCBIN "gfx/trainers/super_nerd.2bpp.lz"
HaunterBackpic:      INCBIN "gfx/pokemon/haunter/back.2bpp.lz"
XatuBackpic:         INCBIN "gfx/pokemon/xatu/back.2bpp.lz"
RedPic:              INCBIN "gfx/trainers/red.2bpp.lz"
Porygon2Backpic:     INCBIN "gfx/pokemon/porygon2/back.2bpp.lz"
JasminePic:          INCBIN "gfx/trainers/jasmine.2bpp.lz"
PinecoBackpic:       INCBIN "gfx/pokemon/pineco/back.2bpp.lz"
MetapodFrontpic:     INCBIN "gfx/pokemon/metapod/front.animated.2bpp.lz"
SeelBackpic:         INCBIN "gfx/pokemon/seel/back.2bpp.lz"
QuagsireBackpic:     INCBIN "gfx/pokemon/quagsire/back.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/whitney.2bpp.lz"
JolteonBackpic:      INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
CaterpieFrontpic:    INCBIN "gfx/pokemon/caterpie/front.animated.2bpp.lz"
HoppipBackpic:       INCBIN "gfx/pokemon/hoppip/back.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/blue.2bpp.lz"
GranbullBackpic:     INCBIN "gfx/pokemon/granbull/back.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/gentleman.2bpp.lz"
ExecutivemPic:       INCBIN "gfx/trainers/executive_m.2bpp.lz"
SpearowBackpic:      INCBIN "gfx/pokemon/spearow/back.2bpp.lz"
SunkernBackpic:      INCBIN "gfx/pokemon/sunkern/back.2bpp.lz"
LaprasBackpic:       INCBIN "gfx/pokemon/lapras/back.2bpp.lz"
MagbyBackpic:        INCBIN "gfx/pokemon/magby/back.2bpp.lz"
DragonairBackpic:    INCBIN "gfx/pokemon/dragonair/back.2bpp.lz"
ZapdosBackpic:       INCBIN "gfx/pokemon/zapdos/back.2bpp.lz"
ChikoritaBackpic:    INCBIN "gfx/pokemon/chikorita/back.2bpp.lz"
CorsolaBackpic:      INCBIN "gfx/pokemon/corsola/back.2bpp.lz"
ChinchouBackpic:     INCBIN "gfx/pokemon/chinchou/back.2bpp.lz"
ChanseyBackpic:      INCBIN "gfx/pokemon/chansey/back.2bpp.lz"
SkiploomBackpic:     INCBIN "gfx/pokemon/skiploom/back.2bpp.lz"
SpinarakFrontpic:    INCBIN "gfx/pokemon/spinarak/front.animated.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/rival2.2bpp.lz"
UnownWFrontpic:      INCBIN "gfx/pokemon/unown_w/front.animated.2bpp.lz"
CharmanderBackpic:   INCBIN "gfx/pokemon/charmander/back.2bpp.lz"
RhyhornBackpic:      INCBIN "gfx/pokemon/rhyhorn/back.2bpp.lz"
UnownCFrontpic:      INCBIN "gfx/pokemon/unown_c/front.animated.2bpp.lz"
MistyPic:            INCBIN "gfx/trainers/misty.2bpp.lz"
BlainePic:           INCBIN "gfx/trainers/blaine.2bpp.lz"
UnownZFrontpic:      INCBIN "gfx/pokemon/unown_z/front.animated.2bpp.lz"
SwinubFrontpic:      INCBIN "gfx/pokemon/swinub/front.animated.2bpp.lz"
LarvitarBackpic:     INCBIN "gfx/pokemon/larvitar/back.2bpp.lz"
PorygonBackpic:      INCBIN "gfx/pokemon/porygon/back.2bpp.lz"
UnownHBackpic:       INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"


SECTION "Pics 17", ROMX

ParasBackpic:        INCBIN "gfx/pokemon/paras/back.2bpp.lz"
VaporeonBackpic:     INCBIN "gfx/pokemon/vaporeon/back.2bpp.lz"
TentacoolBackpic:    INCBIN "gfx/pokemon/tentacool/back.2bpp.lz"
ExecutivefPic:       INCBIN "gfx/trainers/executive_f.2bpp.lz"
BulbasaurBackpic:    INCBIN "gfx/pokemon/bulbasaur/back.2bpp.lz"
SmoochumBackpic:     INCBIN "gfx/pokemon/smoochum/back.2bpp.lz"
PichuBackpic:        INCBIN "gfx/pokemon/pichu/back.2bpp.lz"
HoundoomBackpic:     INCBIN "gfx/pokemon/houndoom/back.2bpp.lz"
BellsproutBackpic:   INCBIN "gfx/pokemon/bellsprout/back.2bpp.lz"
GrimerBackpic:       INCBIN "gfx/pokemon/grimer/back.2bpp.lz"
LanturnBackpic:      INCBIN "gfx/pokemon/lanturn/back.2bpp.lz"
PidgeottoBackpic:    INCBIN "gfx/pokemon/pidgeotto/back.2bpp.lz"
StaryuBackpic:       INCBIN "gfx/pokemon/staryu/back.2bpp.lz"
MrMimeBackpic:       INCBIN "gfx/pokemon/mr__mime/back.2bpp.lz"
CaterpieBackpic:     INCBIN "gfx/pokemon/caterpie/back.2bpp.lz"
VoltorbFrontpic:     INCBIN "gfx/pokemon/voltorb/front.animated.2bpp.lz"
LugiaBackpic:        INCBIN "gfx/pokemon/lugia/back.2bpp.lz"
PrycePic:            INCBIN "gfx/trainers/pryce.2bpp.lz"
BrockPic:            INCBIN "gfx/trainers/brock.2bpp.lz"
UnownGFrontpic:      INCBIN "gfx/pokemon/unown_g/front.animated.2bpp.lz"
ArbokBackpic:        INCBIN "gfx/pokemon/arbok/back.2bpp.lz"
PolitoedBackpic:     INCBIN "gfx/pokemon/politoed/back.2bpp.lz"
DragoniteBackpic:    INCBIN "gfx/pokemon/dragonite/back.2bpp.lz"
HitmonleeBackpic:    INCBIN "gfx/pokemon/hitmonlee/back.2bpp.lz"
NatuFrontpic:        INCBIN "gfx/pokemon/natu/front.animated.2bpp.lz"
UrsaringBackpic:     INCBIN "gfx/pokemon/ursaring/back.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/sage.2bpp.lz"
TeddiursaBackpic:    INCBIN "gfx/pokemon/teddiursa/back.2bpp.lz"
PhanpyBackpic:       INCBIN "gfx/pokemon/phanpy/back.2bpp.lz"
UnownVFrontpic:      INCBIN "gfx/pokemon/unown_v/front.animated.2bpp.lz"
KakunaBackpic:       INCBIN "gfx/pokemon/kakuna/back.2bpp.lz"
WobbuffetBackpic:    INCBIN "gfx/pokemon/wobbuffet/back.2bpp.lz"
TogepiBackpic:       INCBIN "gfx/pokemon/togepi/back.2bpp.lz"
CrobatBackpic:       INCBIN "gfx/pokemon/crobat/back.2bpp.lz"
BlisseyBackpic:      INCBIN "gfx/pokemon/blissey/back.2bpp.lz"
AmpharosBackpic:     INCBIN "gfx/pokemon/ampharos/back.2bpp.lz"
IgglybuffBackpic:    INCBIN "gfx/pokemon/igglybuff/back.2bpp.lz"
AzumarillBackpic:    INCBIN "gfx/pokemon/azumarill/back.2bpp.lz"
OctilleryBackpic:    INCBIN "gfx/pokemon/octillery/back.2bpp.lz"
UnownSFrontpic:      INCBIN "gfx/pokemon/unown_s/front.animated.2bpp.lz"
HorseaBackpic:       INCBIN "gfx/pokemon/horsea/back.2bpp.lz"
SentretBackpic:      INCBIN "gfx/pokemon/sentret/back.2bpp.lz"
UnownOFrontpic:      INCBIN "gfx/pokemon/unown_o/front.animated.2bpp.lz"
UnownTFrontpic:      INCBIN "gfx/pokemon/unown_t/front.animated.2bpp.lz"
WigglytuffBackpic:   INCBIN "gfx/pokemon/wigglytuff/back.2bpp.lz"
ArticunoBackpic:     INCBIN "gfx/pokemon/articuno/back.2bpp.lz"
DittoBackpic:        INCBIN "gfx/pokemon/ditto/back.2bpp.lz"
WeedleBackpic:       INCBIN "gfx/pokemon/weedle/back.2bpp.lz"
UnownHFrontpic:      INCBIN "gfx/pokemon/unown_h/front.animated.2bpp.lz"
CleffaBackpic:       INCBIN "gfx/pokemon/cleffa/back.2bpp.lz"
DrowzeeBackpic:      INCBIN "gfx/pokemon/drowzee/back.2bpp.lz"
GastlyBackpic:       INCBIN "gfx/pokemon/gastly/back.2bpp.lz"
FearowBackpic:       INCBIN "gfx/pokemon/fearow/back.2bpp.lz"
MarillBackpic:       INCBIN "gfx/pokemon/marill/back.2bpp.lz"
DratiniBackpic:      INCBIN "gfx/pokemon/dratini/back.2bpp.lz"
ElectrodeBackpic:    INCBIN "gfx/pokemon/electrode/back.2bpp.lz"
SkarmoryBackpic:     INCBIN "gfx/pokemon/skarmory/back.2bpp.lz"
MetapodBackpic:      INCBIN "gfx/pokemon/metapod/back.2bpp.lz"
JigglypuffBackpic:   INCBIN "gfx/pokemon/jigglypuff/back.2bpp.lz"
OddishBackpic:       INCBIN "gfx/pokemon/oddish/back.2bpp.lz"
UnownDBackpic:       INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"


SECTION "Pics 18", ROMX

SpinarakBackpic:     INCBIN "gfx/pokemon/spinarak/back.2bpp.lz"
RaikouBackpic:       INCBIN "gfx/pokemon/raikou/back.2bpp.lz"
UnownKFrontpic:      INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
HoundourBackpic:     INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
PoliwagBackpic:      INCBIN "gfx/pokemon/poliwag/back.2bpp.lz"
SquirtleBackpic:     INCBIN "gfx/pokemon/squirtle/back.2bpp.lz"
ShuckleBackpic:      INCBIN "gfx/pokemon/shuckle/back.2bpp.lz"
DewgongBackpic:      INCBIN "gfx/pokemon/dewgong/back.2bpp.lz"
UnownBFrontpic:      INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
SlowpokeBackpic:     INCBIN "gfx/pokemon/slowpoke/back.2bpp.lz"
DunsparceBackpic:    INCBIN "gfx/pokemon/dunsparce/back.2bpp.lz"
DonphanBackpic:      INCBIN "gfx/pokemon/donphan/back.2bpp.lz"
WooperBackpic:       INCBIN "gfx/pokemon/wooper/back.2bpp.lz"
TaurosBackpic:       INCBIN "gfx/pokemon/tauros/back.2bpp.lz"
UnownXFrontpic:      INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
UnownNFrontpic:      INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
TangelaBackpic:      INCBIN "gfx/pokemon/tangela/back.2bpp.lz"
VoltorbBackpic:      INCBIN "gfx/pokemon/voltorb/back.2bpp.lz"
UnownJFrontpic:      INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
MantineBackpic:      INCBIN "gfx/pokemon/mantine/back.2bpp.lz"
UnownLFrontpic:      INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
PiloswineBackpic:    INCBIN "gfx/pokemon/piloswine/back.2bpp.lz"
UnownMFrontpic:      INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
UnownFFrontpic:      INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
NatuBackpic:         INCBIN "gfx/pokemon/natu/back.2bpp.lz"
UnownAFrontpic:      INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
GolemBackpic:        INCBIN "gfx/pokemon/golem/back.2bpp.lz"
UnownUFrontpic:      INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
DiglettBackpic:      INCBIN "gfx/pokemon/diglett/back.2bpp.lz"
UnownQFrontpic:      INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
UnownPFrontpic:      INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
UnownCBackpic:       INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
JynxBackpic:         INCBIN "gfx/pokemon/jynx/back.2bpp.lz"
GolbatBackpic:       INCBIN "gfx/pokemon/golbat/back.2bpp.lz"
UnownYFrontpic:      INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
UnownGBackpic:       INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
UnownIFrontpic:      INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
UnownVBackpic:       INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
ForretressBackpic:   INCBIN "gfx/pokemon/forretress/back.2bpp.lz"
UnownSBackpic:       INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
UnownRFrontpic:      INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
UnownEBackpic:       INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
UnownJBackpic:       INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
UnownBBackpic:       INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
UnownOBackpic:       INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
UnownZBackpic:       INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
UnownWBackpic:       INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
UnownNBackpic:       INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
UnownABackpic:       INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
UnownMBackpic:       INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
UnownKBackpic:       INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
UnownTBackpic:       INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
UnownXBackpic:       INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
UnownLBackpic:       INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
UnownUBackpic:       INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
UnownQBackpic:       INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
UnownYBackpic:       INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownPBackpic:       INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
UnownIBackpic:       INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
UnownRBackpic:       INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"
TaurosFrontpic:      INCBIN "gfx/pokemon/tauros/front.animated.2bpp.lz"
VenusaurFrontpic:    INCBIN "gfx/pokemon/venusaur/front.animated.2bpp.lz"
EnteiFrontpic:       INCBIN "gfx/pokemon/entei/front.animated.2bpp.lz"
SuicuneFrontpic:     INCBIN "gfx/pokemon/suicune/front.animated.2bpp.lz"
TyphlosionFrontpic:  INCBIN "gfx/pokemon/typhlosion/front.animated.2bpp.lz"



SECTION "Pics 19", ROMX

YamaskFrontpic:      INCBIN "gfx/pokemon/yamask/front.animated.2bpp.lz"
YamaskBackpic:       INCBIN "gfx/pokemon/yamask/back.2bpp.lz"
CofagrigusFrontpic:  INCBIN "gfx/pokemon/cofagrigus/front.animated.2bpp.lz"
CofagrigusBackpic:   INCBIN "gfx/pokemon/cofagrigus/back.2bpp.lz"
FroakieFrontpic:     INCBIN "gfx/pokemon/froakie/front.animated.2bpp.lz"
FroakieBackpic:      INCBIN "gfx/pokemon/froakie/back.2bpp.lz"
FrogadierFrontpic:   INCBIN "gfx/pokemon/frogadier/front.animated.2bpp.lz"
FrogadierBackpic:    INCBIN "gfx/pokemon/frogadier/back.2bpp.lz"
GreninjaFrontpic:    INCBIN "gfx/pokemon/greninja/front.animated.2bpp.lz"
GreninjaBackpic:     INCBIN "gfx/pokemon/greninja/back.2bpp.lz"
NincadaFrontpic:     INCBIN "gfx/pokemon/nincada/front.animated.2bpp.lz"
NincadaBackpic:      INCBIN "gfx/pokemon/nincada/back.2bpp.lz"
NinjaskFrontpic:     INCBIN "gfx/pokemon/ninjask/front.animated.2bpp.lz"
NinjaskBackpic:      INCBIN "gfx/pokemon/ninjask/back.2bpp.lz"
ShedinjaFrontpic:    INCBIN "gfx/pokemon/shedinja/front.animated.2bpp.lz"
ShedinjaBackpic:     INCBIN "gfx/pokemon/shedinja/back.2bpp.lz"
MegaVenusaurFrontpic: INCBIN "gfx/pokemon/venusaur_mega/front.animated.2bpp.lz"
MegaVenusaurBackpic:  INCBIN "gfx/pokemon/venusaur_mega/back.2bpp.lz"
AronFrontpic:        INCBIN "gfx/pokemon/aron/front.animated.2bpp.lz"
AronBackpic:         INCBIN "gfx/pokemon/aron/back.2bpp.lz"
LaironFrontpic:      INCBIN "gfx/pokemon/lairon/front.animated.2bpp.lz"
LaironBackpic:       INCBIN "gfx/pokemon/lairon/back.2bpp.lz"
AggronFrontpic:      INCBIN "gfx/pokemon/aggron/front.animated.2bpp.lz"
AggronBackpic:       INCBIN "gfx/pokemon/aggron/back.2bpp.lz"
BeldumFrontpic:      INCBIN "gfx/pokemon/beldum/front.animated.2bpp.lz"
BeldumBackpic:       INCBIN "gfx/pokemon/beldum/back.2bpp.lz"
MetangFrontpic:      INCBIN "gfx/pokemon/metang/front.animated.2bpp.lz"
MetangBackpic:       INCBIN "gfx/pokemon/metang/back.2bpp.lz"
MetagrossFrontpic:   INCBIN "gfx/pokemon/metagross/front.animated.2bpp.lz"
MetagrossBackpic:    INCBIN "gfx/pokemon/metagross/back.2bpp.lz"
NosepassFrontpic:    INCBIN "gfx/pokemon/nosepass/front.animated.2bpp.lz"
NosepassBackpic:     INCBIN "gfx/pokemon/nosepass/back.2bpp.lz"
ProbopassFrontpic:   INCBIN "gfx/pokemon/probopass/front.animated.2bpp.lz"
ProbopassBackpic:    INCBIN "gfx/pokemon/probopass/back.2bpp.lz"

SECTION "Pics 20", ROMX

JoltikFrontpic:      INCBIN "gfx/pokemon/joltik/front.animated.2bpp.lz"
JoltikBackpic:       INCBIN "gfx/pokemon/joltik/back.2bpp.lz"
GalvantulaFrontpic:  INCBIN "gfx/pokemon/galvantula/front.animated.2bpp.lz"
GalvantulaBackpic:   INCBIN "gfx/pokemon/galvantula/back.2bpp.lz"
FletchlingFrontpic:  INCBIN "gfx/pokemon/fletchling/front.animated.2bpp.lz"
FletchlingBackpic:   INCBIN "gfx/pokemon/fletchling/back.2bpp.lz"
FletchindrFrontpic:  INCBIN "gfx/pokemon/fletchindr/front.animated.2bpp.lz"
FletchindrBackpic:   INCBIN "gfx/pokemon/fletchindr/back.2bpp.lz"
TalonflameFrontpic:  INCBIN "gfx/pokemon/talonflame/front.animated.2bpp.lz"
TalonflameBackpic:   INCBIN "gfx/pokemon/talonflame/back.2bpp.lz"
LittenFrontpic:      INCBIN "gfx/pokemon/litten/front.animated.2bpp.lz"
LittenBackpic:       INCBIN "gfx/pokemon/litten/back.2bpp.lz"
TorracatFrontpic:    INCBIN "gfx/pokemon/torracat/front.animated.2bpp.lz"
TorracatBackpic:     INCBIN "gfx/pokemon/torracat/back.2bpp.lz"
IncineroarFrontpic:  INCBIN "gfx/pokemon/incineroar/front.animated.2bpp.lz"
IncineroarBackpic:   INCBIN "gfx/pokemon/incineroar/back.2bpp.lz"
ApplinFrontpic:      INCBIN "gfx/pokemon/applin/front.animated.2bpp.lz"
ApplinBackpic:       INCBIN "gfx/pokemon/applin/back.2bpp.lz"
FlappleFrontpic:     INCBIN "gfx/pokemon/flapple/front.animated.2bpp.lz"
FlappleBackpic:      INCBIN "gfx/pokemon/flapple/back.2bpp.lz"
AppletunFrontpic:    INCBIN "gfx/pokemon/appletun/front.animated.2bpp.lz"
AppletunBackpic:     INCBIN "gfx/pokemon/appletun/back.2bpp.lz"
DreepyFrontpic:      INCBIN "gfx/pokemon/dreepy/front.animated.2bpp.lz"
DreepyBackpic:       INCBIN "gfx/pokemon/dreepy/back.2bpp.lz"
DrakloakFrontpic:    INCBIN "gfx/pokemon/drakloak/front.animated.2bpp.lz"
DrakloakBackpic:     INCBIN "gfx/pokemon/drakloak/back.2bpp.lz"
DragapultFrontpic:   INCBIN "gfx/pokemon/dragapult/front.animated.2bpp.lz"
DragapultBackpic:    INCBIN "gfx/pokemon/dragapult/back.2bpp.lz"
MudkipFrontpic:      INCBIN "gfx/pokemon/mudkip/front.animated.2bpp.lz"
MudkipBackpic:       INCBIN "gfx/pokemon/mudkip/back.2bpp.lz"
MarshtompFrontpic:   INCBIN "gfx/pokemon/marshtomp/front.animated.2bpp.lz"
MarshtompBackpic:    INCBIN "gfx/pokemon/marshtomp/back.2bpp.lz"
SwampertFrontpic:    INCBIN "gfx/pokemon/swampert/front.animated.2bpp.lz"
SwampertBackpic:     INCBIN "gfx/pokemon/swampert/back.2bpp.lz"

SECTION "Pics 21", ROMX

WeavileFrontpic:     INCBIN "gfx/pokemon/weavile/front.animated.2bpp.lz"
WeavileBackpic:      INCBIN "gfx/pokemon/weavile/back.2bpp.lz"
HonchkrowFrontpic:   INCBIN "gfx/pokemon/honchkrow/front.animated.2bpp.lz"
HonchkrowBackpic:    INCBIN "gfx/pokemon/honchkrow/back.2bpp.lz"
GalarianArticunoFrontpic: INCBIN "gfx/pokemon/articuno_galar/front.animated.2bpp.lz"
GalarianArticunoBackpic:  INCBIN "gfx/pokemon/articuno_galar/back.2bpp.lz"
MegaAmpharosFrontpic: INCBIN "gfx/pokemon/ampharos_mega/front.animated.2bpp.lz"
MegaAmpharosBackpic:  INCBIN "gfx/pokemon/ampharos_mega/back.2bpp.lz"
Mon127Frontpic:      INCBIN "gfx/pokemon/mon_127/front.animated.2bpp.lz"
Mon127Backpic:       INCBIN "gfx/pokemon/mon_127/back.2bpp.lz"
Mon128Frontpic:      INCBIN "gfx/pokemon/mon_128/front.animated.2bpp.lz"
Mon128Backpic:       INCBIN "gfx/pokemon/mon_128/back.2bpp.lz"
Mon129Frontpic:      INCBIN "gfx/pokemon/mon_129/front.animated.2bpp.lz"
Mon129Backpic:       INCBIN "gfx/pokemon/mon_129/back.2bpp.lz"
Mon12AFrontpic:      INCBIN "gfx/pokemon/mon_12A/front.animated.2bpp.lz"
Mon12ABackpic:       INCBIN "gfx/pokemon/mon_12A/back.2bpp.lz"
Mon12BFrontpic:      INCBIN "gfx/pokemon/mon_12B/front.animated.2bpp.lz"
Mon12BBackpic:       INCBIN "gfx/pokemon/mon_12B/back.2bpp.lz"
Mon12CFrontpic:      INCBIN "gfx/pokemon/mon_12C/front.animated.2bpp.lz"
Mon12CBackpic:       INCBIN "gfx/pokemon/mon_12C/back.2bpp.lz"
Mon12DFrontpic:      INCBIN "gfx/pokemon/mon_12D/front.animated.2bpp.lz"
Mon12DBackpic:       INCBIN "gfx/pokemon/mon_12D/back.2bpp.lz"
Mon12EFrontpic:      INCBIN "gfx/pokemon/mon_12E/front.animated.2bpp.lz"
Mon12EBackpic:       INCBIN "gfx/pokemon/mon_12E/back.2bpp.lz"
Mon12FFrontpic:      INCBIN "gfx/pokemon/mon_12F/front.animated.2bpp.lz"
Mon12FBackpic:       INCBIN "gfx/pokemon/mon_12F/back.2bpp.lz"
Mon130Frontpic:      INCBIN "gfx/pokemon/mon_130/front.animated.2bpp.lz"
Mon130Backpic:       INCBIN "gfx/pokemon/mon_130/back.2bpp.lz"
Mon131Frontpic:      INCBIN "gfx/pokemon/mon_131/front.animated.2bpp.lz"
Mon131Backpic:       INCBIN "gfx/pokemon/mon_131/back.2bpp.lz"
Mon132Frontpic:      INCBIN "gfx/pokemon/mon_132/front.animated.2bpp.lz"
Mon132Backpic:       INCBIN "gfx/pokemon/mon_132/back.2bpp.lz"
Mon133Frontpic:      INCBIN "gfx/pokemon/mon_133/front.animated.2bpp.lz"
Mon133Backpic:       INCBIN "gfx/pokemon/mon_133/back.2bpp.lz"
Mon134Frontpic:      INCBIN "gfx/pokemon/mon_134/front.animated.2bpp.lz"
Mon134Backpic:       INCBIN "gfx/pokemon/mon_134/back.2bpp.lz"
Mon135Frontpic:      INCBIN "gfx/pokemon/mon_135/front.animated.2bpp.lz"
Mon135Backpic:       INCBIN "gfx/pokemon/mon_135/back.2bpp.lz"
Mon136Frontpic:      INCBIN "gfx/pokemon/mon_136/front.animated.2bpp.lz"
Mon136Backpic:       INCBIN "gfx/pokemon/mon_136/back.2bpp.lz"
Mon137Frontpic:      INCBIN "gfx/pokemon/mon_137/front.animated.2bpp.lz"
Mon137Backpic:       INCBIN "gfx/pokemon/mon_137/back.2bpp.lz"
Mon138Frontpic:      INCBIN "gfx/pokemon/mon_138/front.animated.2bpp.lz"
Mon138Backpic:       INCBIN "gfx/pokemon/mon_138/back.2bpp.lz"
Mon139Frontpic:      INCBIN "gfx/pokemon/mon_139/front.animated.2bpp.lz"
Mon139Backpic:       INCBIN "gfx/pokemon/mon_139/back.2bpp.lz"

SECTION "Pics 22", ROMX

Mon13AFrontpic:      INCBIN "gfx/pokemon/mon_13A/front.animated.2bpp.lz"
Mon13ABackpic:       INCBIN "gfx/pokemon/mon_13A/back.2bpp.lz"
Mon13BFrontpic:      INCBIN "gfx/pokemon/mon_13B/front.animated.2bpp.lz"
Mon13BBackpic:       INCBIN "gfx/pokemon/mon_13B/back.2bpp.lz"
Mon13CFrontpic:      INCBIN "gfx/pokemon/mon_13C/front.animated.2bpp.lz"
Mon13CBackpic:       INCBIN "gfx/pokemon/mon_13C/back.2bpp.lz"
Mon13DFrontpic:      INCBIN "gfx/pokemon/mon_13D/front.animated.2bpp.lz"
Mon13DBackpic:       INCBIN "gfx/pokemon/mon_13D/back.2bpp.lz"
Mon13EFrontpic:      INCBIN "gfx/pokemon/mon_13E/front.animated.2bpp.lz"
Mon13EBackpic:       INCBIN "gfx/pokemon/mon_13E/back.2bpp.lz"
Mon13FFrontpic:      INCBIN "gfx/pokemon/mon_13F/front.animated.2bpp.lz"
Mon13FBackpic:       INCBIN "gfx/pokemon/mon_13F/back.2bpp.lz"
Mon140Frontpic:      INCBIN "gfx/pokemon/mon_140/front.animated.2bpp.lz"
Mon140Backpic:       INCBIN "gfx/pokemon/mon_140/back.2bpp.lz"
Mon141Frontpic:      INCBIN "gfx/pokemon/mon_141/front.animated.2bpp.lz"
Mon141Backpic:       INCBIN "gfx/pokemon/mon_141/back.2bpp.lz"
Mon142Frontpic:      INCBIN "gfx/pokemon/mon_142/front.animated.2bpp.lz"
Mon142Backpic:       INCBIN "gfx/pokemon/mon_142/back.2bpp.lz"

SECTION "Pics 23", ROMX

Mon143Frontpic:      INCBIN "gfx/pokemon/mon_143/front.animated.2bpp.lz"
Mon143Backpic:       INCBIN "gfx/pokemon/mon_143/back.2bpp.lz"
Mon144Frontpic:      INCBIN "gfx/pokemon/mon_144/front.animated.2bpp.lz"
Mon144Backpic:       INCBIN "gfx/pokemon/mon_144/back.2bpp.lz"
Mon145Frontpic:      INCBIN "gfx/pokemon/mon_145/front.animated.2bpp.lz"
Mon145Backpic:       INCBIN "gfx/pokemon/mon_145/back.2bpp.lz"
Mon146Frontpic:      INCBIN "gfx/pokemon/mon_146/front.animated.2bpp.lz"
Mon146Backpic:       INCBIN "gfx/pokemon/mon_146/back.2bpp.lz"
Mon147Frontpic:      INCBIN "gfx/pokemon/mon_147/front.animated.2bpp.lz"
Mon147Backpic:       INCBIN "gfx/pokemon/mon_147/back.2bpp.lz"
Mon148Frontpic:      INCBIN "gfx/pokemon/mon_148/front.animated.2bpp.lz"
Mon148Backpic:       INCBIN "gfx/pokemon/mon_148/back.2bpp.lz"
Mon149Frontpic:      INCBIN "gfx/pokemon/mon_149/front.animated.2bpp.lz"
Mon149Backpic:       INCBIN "gfx/pokemon/mon_149/back.2bpp.lz"
Mon14AFrontpic:      INCBIN "gfx/pokemon/mon_14A/front.animated.2bpp.lz"
Mon14ABackpic:       INCBIN "gfx/pokemon/mon_14A/back.2bpp.lz"
Mon14BFrontpic:      INCBIN "gfx/pokemon/mon_14B/front.animated.2bpp.lz"
Mon14BBackpic:       INCBIN "gfx/pokemon/mon_14B/back.2bpp.lz"
Mon14CFrontpic:      INCBIN "gfx/pokemon/mon_14C/front.animated.2bpp.lz"
Mon14CBackpic:       INCBIN "gfx/pokemon/mon_14C/back.2bpp.lz"
Mon14DFrontpic:      INCBIN "gfx/pokemon/mon_14D/front.animated.2bpp.lz"
Mon14DBackpic:       INCBIN "gfx/pokemon/mon_14D/back.2bpp.lz"
Mon14EFrontpic:      INCBIN "gfx/pokemon/mon_14E/front.animated.2bpp.lz"
Mon14EBackpic:       INCBIN "gfx/pokemon/mon_14E/back.2bpp.lz"
Mon14FFrontpic:      INCBIN "gfx/pokemon/mon_14F/front.animated.2bpp.lz"
Mon14FBackpic:       INCBIN "gfx/pokemon/mon_14F/back.2bpp.lz"
Mon150Frontpic:      INCBIN "gfx/pokemon/mon_150/front.animated.2bpp.lz"
Mon150Backpic:       INCBIN "gfx/pokemon/mon_150/back.2bpp.lz"
Mon151Frontpic:      INCBIN "gfx/pokemon/mon_151/front.animated.2bpp.lz"
Mon151Backpic:       INCBIN "gfx/pokemon/mon_151/back.2bpp.lz"
Mon152Frontpic:      INCBIN "gfx/pokemon/mon_152/front.animated.2bpp.lz"
Mon152Backpic:       INCBIN "gfx/pokemon/mon_152/back.2bpp.lz"

SECTION "Pics 24", ROMX

Mon153Frontpic:      INCBIN "gfx/pokemon/mon_153/front.animated.2bpp.lz"
Mon153Backpic:       INCBIN "gfx/pokemon/mon_153/back.2bpp.lz"
Mon154Frontpic:      INCBIN "gfx/pokemon/mon_154/front.animated.2bpp.lz"
Mon154Backpic:       INCBIN "gfx/pokemon/mon_154/back.2bpp.lz"
Mon155Frontpic:      INCBIN "gfx/pokemon/mon_155/front.animated.2bpp.lz"
Mon155Backpic:       INCBIN "gfx/pokemon/mon_155/back.2bpp.lz"
Mon156Frontpic:      INCBIN "gfx/pokemon/mon_156/front.animated.2bpp.lz"
Mon156Backpic:       INCBIN "gfx/pokemon/mon_156/back.2bpp.lz"
Mon157Frontpic:      INCBIN "gfx/pokemon/mon_157/front.animated.2bpp.lz"
Mon157Backpic:       INCBIN "gfx/pokemon/mon_157/back.2bpp.lz"
Mon158Frontpic:      INCBIN "gfx/pokemon/mon_158/front.animated.2bpp.lz"
Mon158Backpic:       INCBIN "gfx/pokemon/mon_158/back.2bpp.lz"
Mon159Frontpic:      INCBIN "gfx/pokemon/mon_159/front.animated.2bpp.lz"
Mon159Backpic:       INCBIN "gfx/pokemon/mon_159/back.2bpp.lz"
Mon15AFrontpic:      INCBIN "gfx/pokemon/mon_15A/front.animated.2bpp.lz"
Mon15ABackpic:       INCBIN "gfx/pokemon/mon_15A/back.2bpp.lz"
Mon15BFrontpic:      INCBIN "gfx/pokemon/mon_15B/front.animated.2bpp.lz"
Mon15BBackpic:       INCBIN "gfx/pokemon/mon_15B/back.2bpp.lz"
Mon15CFrontpic:      INCBIN "gfx/pokemon/mon_15C/front.animated.2bpp.lz"
Mon15CBackpic:       INCBIN "gfx/pokemon/mon_15C/back.2bpp.lz"
Mon15DFrontpic:      INCBIN "gfx/pokemon/mon_15D/front.animated.2bpp.lz"
Mon15DBackpic:       INCBIN "gfx/pokemon/mon_15D/back.2bpp.lz"
Mon15EFrontpic:      INCBIN "gfx/pokemon/mon_15E/front.animated.2bpp.lz"
Mon15EBackpic:       INCBIN "gfx/pokemon/mon_15E/back.2bpp.lz"
Mon15FFrontpic:      INCBIN "gfx/pokemon/mon_15F/front.animated.2bpp.lz"
Mon15FBackpic:       INCBIN "gfx/pokemon/mon_15F/back.2bpp.lz"

SECTION "Pics 25", ROMX

Mon160Frontpic:      INCBIN "gfx/pokemon/mon_160/front.animated.2bpp.lz"
Mon160Backpic:       INCBIN "gfx/pokemon/mon_160/back.2bpp.lz"
Mon161Frontpic:      INCBIN "gfx/pokemon/mon_161/front.animated.2bpp.lz"
Mon161Backpic:       INCBIN "gfx/pokemon/mon_161/back.2bpp.lz"
Mon162Frontpic:      INCBIN "gfx/pokemon/mon_162/front.animated.2bpp.lz"
Mon162Backpic:       INCBIN "gfx/pokemon/mon_162/back.2bpp.lz"
Mon163Frontpic:      INCBIN "gfx/pokemon/mon_163/front.animated.2bpp.lz"
Mon163Backpic:       INCBIN "gfx/pokemon/mon_163/back.2bpp.lz"
Mon164Frontpic:      INCBIN "gfx/pokemon/mon_164/front.animated.2bpp.lz"
Mon164Backpic:       INCBIN "gfx/pokemon/mon_164/back.2bpp.lz"
Mon165Frontpic:      INCBIN "gfx/pokemon/mon_165/front.animated.2bpp.lz"
Mon165Backpic:       INCBIN "gfx/pokemon/mon_165/back.2bpp.lz"
Mon166Frontpic:      INCBIN "gfx/pokemon/mon_166/front.animated.2bpp.lz"
Mon166Backpic:       INCBIN "gfx/pokemon/mon_166/back.2bpp.lz"
Mon167Frontpic:      INCBIN "gfx/pokemon/mon_167/front.animated.2bpp.lz"
Mon167Backpic:       INCBIN "gfx/pokemon/mon_167/back.2bpp.lz"
Mon168Frontpic:      INCBIN "gfx/pokemon/mon_168/front.animated.2bpp.lz"
Mon168Backpic:       INCBIN "gfx/pokemon/mon_168/back.2bpp.lz"
Mon169Frontpic:      INCBIN "gfx/pokemon/mon_169/front.animated.2bpp.lz"
Mon169Backpic:       INCBIN "gfx/pokemon/mon_169/back.2bpp.lz"
Mon16AFrontpic:      INCBIN "gfx/pokemon/mon_16A/front.animated.2bpp.lz"
Mon16ABackpic:       INCBIN "gfx/pokemon/mon_16A/back.2bpp.lz"
Mon16BFrontpic:      INCBIN "gfx/pokemon/mon_16B/front.animated.2bpp.lz"
Mon16BBackpic:       INCBIN "gfx/pokemon/mon_16B/back.2bpp.lz"
Mon16CFrontpic:      INCBIN "gfx/pokemon/mon_16C/front.animated.2bpp.lz"
Mon16CBackpic:       INCBIN "gfx/pokemon/mon_16C/back.2bpp.lz"
Mon16DFrontpic:      INCBIN "gfx/pokemon/mon_16D/front.animated.2bpp.lz"
Mon16DBackpic:       INCBIN "gfx/pokemon/mon_16D/back.2bpp.lz"
Mon16EFrontpic:      INCBIN "gfx/pokemon/mon_16E/front.animated.2bpp.lz"
Mon16EBackpic:       INCBIN "gfx/pokemon/mon_16E/back.2bpp.lz"
Mon16FFrontpic:      INCBIN "gfx/pokemon/mon_16F/front.animated.2bpp.lz"
Mon16FBackpic:       INCBIN "gfx/pokemon/mon_16F/back.2bpp.lz"
Mon170Frontpic:      INCBIN "gfx/pokemon/mon_170/front.animated.2bpp.lz"
Mon170Backpic:       INCBIN "gfx/pokemon/mon_170/back.2bpp.lz"
Mon171Frontpic:      INCBIN "gfx/pokemon/mon_171/front.animated.2bpp.lz"
Mon171Backpic:       INCBIN "gfx/pokemon/mon_171/back.2bpp.lz"
Mon172Frontpic:      INCBIN "gfx/pokemon/mon_172/front.animated.2bpp.lz"
Mon172Backpic:       INCBIN "gfx/pokemon/mon_172/back.2bpp.lz"
Mon173Frontpic:      INCBIN "gfx/pokemon/mon_173/front.animated.2bpp.lz"
Mon173Backpic:       INCBIN "gfx/pokemon/mon_173/back.2bpp.lz"
Mon174Frontpic:      INCBIN "gfx/pokemon/mon_174/front.animated.2bpp.lz"
Mon174Backpic:       INCBIN "gfx/pokemon/mon_174/back.2bpp.lz"
Mon175Frontpic:      INCBIN "gfx/pokemon/mon_175/front.animated.2bpp.lz"
Mon175Backpic:       INCBIN "gfx/pokemon/mon_175/back.2bpp.lz"
Mon176Frontpic:      INCBIN "gfx/pokemon/mon_176/front.animated.2bpp.lz"
Mon176Backpic:       INCBIN "gfx/pokemon/mon_176/back.2bpp.lz"
Mon177Frontpic:      INCBIN "gfx/pokemon/mon_177/front.animated.2bpp.lz"
Mon177Backpic:       INCBIN "gfx/pokemon/mon_177/back.2bpp.lz"

SECTION "Pics 26", ROMX

Mon178Frontpic:      INCBIN "gfx/pokemon/mon_178/front.animated.2bpp.lz"
Mon178Backpic:       INCBIN "gfx/pokemon/mon_178/back.2bpp.lz"
Mon179Frontpic:      INCBIN "gfx/pokemon/mon_179/front.animated.2bpp.lz"
Mon179Backpic:       INCBIN "gfx/pokemon/mon_179/back.2bpp.lz"
Mon17AFrontpic:      INCBIN "gfx/pokemon/mon_17A/front.animated.2bpp.lz"
Mon17ABackpic:       INCBIN "gfx/pokemon/mon_17A/back.2bpp.lz"
Mon17BFrontpic:      INCBIN "gfx/pokemon/mon_17B/front.animated.2bpp.lz"
Mon17BBackpic:       INCBIN "gfx/pokemon/mon_17B/back.2bpp.lz"
Mon17CFrontpic:      INCBIN "gfx/pokemon/mon_17C/front.animated.2bpp.lz"
Mon17CBackpic:       INCBIN "gfx/pokemon/mon_17C/back.2bpp.lz"
Mon17DFrontpic:      INCBIN "gfx/pokemon/mon_17D/front.animated.2bpp.lz"
Mon17DBackpic:       INCBIN "gfx/pokemon/mon_17D/back.2bpp.lz"
Mon17EFrontpic:      INCBIN "gfx/pokemon/mon_17E/front.animated.2bpp.lz"
Mon17EBackpic:       INCBIN "gfx/pokemon/mon_17E/back.2bpp.lz"
Mon17FFrontpic:      INCBIN "gfx/pokemon/mon_17F/front.animated.2bpp.lz"
Mon17FBackpic:       INCBIN "gfx/pokemon/mon_17F/back.2bpp.lz"
Mon180Frontpic:      INCBIN "gfx/pokemon/mon_180/front.animated.2bpp.lz"
Mon180Backpic:       INCBIN "gfx/pokemon/mon_180/back.2bpp.lz"
Mon181Frontpic:      INCBIN "gfx/pokemon/mon_181/front.animated.2bpp.lz"
Mon181Backpic:       INCBIN "gfx/pokemon/mon_181/back.2bpp.lz"
Mon182Frontpic:      INCBIN "gfx/pokemon/mon_182/front.animated.2bpp.lz"
Mon182Backpic:       INCBIN "gfx/pokemon/mon_182/back.2bpp.lz"
Mon183Frontpic:      INCBIN "gfx/pokemon/mon_183/front.animated.2bpp.lz"
Mon183Backpic:       INCBIN "gfx/pokemon/mon_183/back.2bpp.lz"
Mon184Frontpic:      INCBIN "gfx/pokemon/mon_184/front.animated.2bpp.lz"
Mon184Backpic:       INCBIN "gfx/pokemon/mon_184/back.2bpp.lz"
Mon185Frontpic:      INCBIN "gfx/pokemon/mon_185/front.animated.2bpp.lz"
Mon185Backpic:       INCBIN "gfx/pokemon/mon_185/back.2bpp.lz"
Mon186Frontpic:      INCBIN "gfx/pokemon/mon_186/front.animated.2bpp.lz"
Mon186Backpic:       INCBIN "gfx/pokemon/mon_186/back.2bpp.lz"

SECTION "Pics 27", ROMX

Mon187Frontpic:      INCBIN "gfx/pokemon/mon_187/front.animated.2bpp.lz"
Mon187Backpic:       INCBIN "gfx/pokemon/mon_187/back.2bpp.lz"
Mon188Frontpic:      INCBIN "gfx/pokemon/mon_188/front.animated.2bpp.lz"
Mon188Backpic:       INCBIN "gfx/pokemon/mon_188/back.2bpp.lz"
Mon189Frontpic:      INCBIN "gfx/pokemon/mon_189/front.animated.2bpp.lz"
Mon189Backpic:       INCBIN "gfx/pokemon/mon_189/back.2bpp.lz"
Mon18AFrontpic:      INCBIN "gfx/pokemon/mon_18A/front.animated.2bpp.lz"
Mon18ABackpic:       INCBIN "gfx/pokemon/mon_18A/back.2bpp.lz"
Mon18BFrontpic:      INCBIN "gfx/pokemon/mon_18B/front.animated.2bpp.lz"
Mon18BBackpic:       INCBIN "gfx/pokemon/mon_18B/back.2bpp.lz"
Mon18CFrontpic:      INCBIN "gfx/pokemon/mon_18C/front.animated.2bpp.lz"
Mon18CBackpic:       INCBIN "gfx/pokemon/mon_18C/back.2bpp.lz"
Mon18DFrontpic:      INCBIN "gfx/pokemon/mon_18D/front.animated.2bpp.lz"
Mon18DBackpic:       INCBIN "gfx/pokemon/mon_18D/back.2bpp.lz"

SECTION "Pics 28", ROMX

Mon18EFrontpic:      INCBIN "gfx/pokemon/mon_18E/front.animated.2bpp.lz"
Mon18EBackpic:       INCBIN "gfx/pokemon/mon_18E/back.2bpp.lz"
Mon18FFrontpic:      INCBIN "gfx/pokemon/mon_18F/front.animated.2bpp.lz"
Mon18FBackpic:       INCBIN "gfx/pokemon/mon_18F/back.2bpp.lz"
Mon190Frontpic:      INCBIN "gfx/pokemon/mon_190/front.animated.2bpp.lz"
Mon190Backpic:       INCBIN "gfx/pokemon/mon_190/back.2bpp.lz"
Mon191Frontpic:      INCBIN "gfx/pokemon/mon_191/front.animated.2bpp.lz"
Mon191Backpic:       INCBIN "gfx/pokemon/mon_191/back.2bpp.lz"
Mon192Frontpic:      INCBIN "gfx/pokemon/mon_192/front.animated.2bpp.lz"
Mon192Backpic:       INCBIN "gfx/pokemon/mon_192/back.2bpp.lz"
Mon193Frontpic:      INCBIN "gfx/pokemon/mon_193/front.animated.2bpp.lz"
Mon193Backpic:       INCBIN "gfx/pokemon/mon_193/back.2bpp.lz"
Mon194Frontpic:      INCBIN "gfx/pokemon/mon_194/front.animated.2bpp.lz"
Mon194Backpic:       INCBIN "gfx/pokemon/mon_194/back.2bpp.lz"
Mon195Frontpic:      INCBIN "gfx/pokemon/mon_195/front.animated.2bpp.lz"
Mon195Backpic:       INCBIN "gfx/pokemon/mon_195/back.2bpp.lz"
Mon196Frontpic:      INCBIN "gfx/pokemon/mon_196/front.animated.2bpp.lz"
Mon196Backpic:       INCBIN "gfx/pokemon/mon_196/back.2bpp.lz"
Mon197Frontpic:      INCBIN "gfx/pokemon/mon_197/front.animated.2bpp.lz"
Mon197Backpic:       INCBIN "gfx/pokemon/mon_197/back.2bpp.lz"
Mon198Frontpic:      INCBIN "gfx/pokemon/mon_198/front.animated.2bpp.lz"
Mon198Backpic:       INCBIN "gfx/pokemon/mon_198/back.2bpp.lz"
Mon199Frontpic:      INCBIN "gfx/pokemon/mon_199/front.animated.2bpp.lz"
Mon199Backpic:       INCBIN "gfx/pokemon/mon_199/back.2bpp.lz"
Mon19AFrontpic:      INCBIN "gfx/pokemon/mon_19A/front.animated.2bpp.lz"
Mon19ABackpic:       INCBIN "gfx/pokemon/mon_19A/back.2bpp.lz"
Mon19BFrontpic:      INCBIN "gfx/pokemon/mon_19B/front.animated.2bpp.lz"
Mon19BBackpic:       INCBIN "gfx/pokemon/mon_19B/back.2bpp.lz"
Mon19CFrontpic:      INCBIN "gfx/pokemon/mon_19C/front.animated.2bpp.lz"
Mon19CBackpic:       INCBIN "gfx/pokemon/mon_19C/back.2bpp.lz"
Mon19DFrontpic:      INCBIN "gfx/pokemon/mon_19D/front.animated.2bpp.lz"
Mon19DBackpic:       INCBIN "gfx/pokemon/mon_19D/back.2bpp.lz"
Mon19EFrontpic:      INCBIN "gfx/pokemon/mon_19E/front.animated.2bpp.lz"
Mon19EBackpic:       INCBIN "gfx/pokemon/mon_19E/back.2bpp.lz"
Mon19FFrontpic:      INCBIN "gfx/pokemon/mon_19F/front.animated.2bpp.lz"
Mon19FBackpic:       INCBIN "gfx/pokemon/mon_19F/back.2bpp.lz"
Mon1A0Frontpic:      INCBIN "gfx/pokemon/mon_1A0/front.animated.2bpp.lz"
Mon1A0Backpic:       INCBIN "gfx/pokemon/mon_1A0/back.2bpp.lz"
Mon1A1Frontpic:      INCBIN "gfx/pokemon/mon_1A1/front.animated.2bpp.lz"
Mon1A1Backpic:       INCBIN "gfx/pokemon/mon_1A1/back.2bpp.lz"
Mon1A2Frontpic:      INCBIN "gfx/pokemon/mon_1A2/front.animated.2bpp.lz"
Mon1A2Backpic:       INCBIN "gfx/pokemon/mon_1A2/back.2bpp.lz"
Mon1A3Frontpic:      INCBIN "gfx/pokemon/mon_1A3/front.animated.2bpp.lz"
Mon1A3Backpic:       INCBIN "gfx/pokemon/mon_1A3/back.2bpp.lz"
Mon1A4Frontpic:      INCBIN "gfx/pokemon/mon_1A4/front.animated.2bpp.lz"
Mon1A4Backpic:       INCBIN "gfx/pokemon/mon_1A4/back.2bpp.lz"
Mon1A5Frontpic:      INCBIN "gfx/pokemon/mon_1A5/front.animated.2bpp.lz"
Mon1A5Backpic:       INCBIN "gfx/pokemon/mon_1A5/back.2bpp.lz"

SECTION "Pics 29", ROMX

Mon1A6Frontpic:      INCBIN "gfx/pokemon/mon_1A6/front.animated.2bpp.lz"
Mon1A6Backpic:       INCBIN "gfx/pokemon/mon_1A6/back.2bpp.lz"
Mon1A7Frontpic:      INCBIN "gfx/pokemon/mon_1A7/front.animated.2bpp.lz"
Mon1A7Backpic:       INCBIN "gfx/pokemon/mon_1A7/back.2bpp.lz"
Mon1A8Frontpic:      INCBIN "gfx/pokemon/mon_1A8/front.animated.2bpp.lz"
Mon1A8Backpic:       INCBIN "gfx/pokemon/mon_1A8/back.2bpp.lz"
Mon1A9Frontpic:      INCBIN "gfx/pokemon/mon_1A9/front.animated.2bpp.lz"
Mon1A9Backpic:       INCBIN "gfx/pokemon/mon_1A9/back.2bpp.lz"
Mon1AAFrontpic:      INCBIN "gfx/pokemon/mon_1AA/front.animated.2bpp.lz"
Mon1AABackpic:       INCBIN "gfx/pokemon/mon_1AA/back.2bpp.lz"
Mon1ABFrontpic:      INCBIN "gfx/pokemon/mon_1AB/front.animated.2bpp.lz"
Mon1ABBackpic:       INCBIN "gfx/pokemon/mon_1AB/back.2bpp.lz"
Mon1ACFrontpic:      INCBIN "gfx/pokemon/mon_1AC/front.animated.2bpp.lz"
Mon1ACBackpic:       INCBIN "gfx/pokemon/mon_1AC/back.2bpp.lz"
Mon1ADFrontpic:      INCBIN "gfx/pokemon/mon_1AD/front.animated.2bpp.lz"
Mon1ADBackpic:       INCBIN "gfx/pokemon/mon_1AD/back.2bpp.lz"
Mon1AEFrontpic:      INCBIN "gfx/pokemon/mon_1AE/front.animated.2bpp.lz"
Mon1AEBackpic:       INCBIN "gfx/pokemon/mon_1AE/back.2bpp.lz"
Mon1AFFrontpic:      INCBIN "gfx/pokemon/mon_1AF/front.animated.2bpp.lz"
Mon1AFBackpic:       INCBIN "gfx/pokemon/mon_1AF/back.2bpp.lz"
Mon1B0Frontpic:      INCBIN "gfx/pokemon/mon_1B0/front.animated.2bpp.lz"
Mon1B0Backpic:       INCBIN "gfx/pokemon/mon_1B0/back.2bpp.lz"
Mon1B1Frontpic:      INCBIN "gfx/pokemon/mon_1B1/front.animated.2bpp.lz"
Mon1B1Backpic:       INCBIN "gfx/pokemon/mon_1B1/back.2bpp.lz"
Mon1B2Frontpic:      INCBIN "gfx/pokemon/mon_1B2/front.animated.2bpp.lz"
Mon1B2Backpic:       INCBIN "gfx/pokemon/mon_1B2/back.2bpp.lz"
Mon1B3Frontpic:      INCBIN "gfx/pokemon/mon_1B3/front.animated.2bpp.lz"
Mon1B3Backpic:       INCBIN "gfx/pokemon/mon_1B3/back.2bpp.lz"
Mon1B4Frontpic:      INCBIN "gfx/pokemon/mon_1B4/front.animated.2bpp.lz"
Mon1B4Backpic:       INCBIN "gfx/pokemon/mon_1B4/back.2bpp.lz"
Mon1B5Frontpic:      INCBIN "gfx/pokemon/mon_1B5/front.animated.2bpp.lz"
Mon1B5Backpic:       INCBIN "gfx/pokemon/mon_1B5/back.2bpp.lz"
Mon1B6Frontpic:      INCBIN "gfx/pokemon/mon_1B6/front.animated.2bpp.lz"
Mon1B6Backpic:       INCBIN "gfx/pokemon/mon_1B6/back.2bpp.lz"
Mon1B7Frontpic:      INCBIN "gfx/pokemon/mon_1B7/front.animated.2bpp.lz"
Mon1B7Backpic:       INCBIN "gfx/pokemon/mon_1B7/back.2bpp.lz"
Mon1B8Frontpic:      INCBIN "gfx/pokemon/mon_1B8/front.animated.2bpp.lz"
Mon1B8Backpic:       INCBIN "gfx/pokemon/mon_1B8/back.2bpp.lz"
Mon1B9Frontpic:      INCBIN "gfx/pokemon/mon_1B9/front.animated.2bpp.lz"
Mon1B9Backpic:       INCBIN "gfx/pokemon/mon_1B9/back.2bpp.lz"
Mon1BAFrontpic:      INCBIN "gfx/pokemon/mon_1BA/front.animated.2bpp.lz"
Mon1BABackpic:       INCBIN "gfx/pokemon/mon_1BA/back.2bpp.lz"
Mon1BBFrontpic:      INCBIN "gfx/pokemon/mon_1BB/front.animated.2bpp.lz"
Mon1BBBackpic:       INCBIN "gfx/pokemon/mon_1BB/back.2bpp.lz"
Mon1BCFrontpic:      INCBIN "gfx/pokemon/mon_1BC/front.animated.2bpp.lz"
Mon1BCBackpic:       INCBIN "gfx/pokemon/mon_1BC/back.2bpp.lz"
Mon1BDFrontpic:      INCBIN "gfx/pokemon/mon_1BD/front.animated.2bpp.lz"
Mon1BDBackpic:       INCBIN "gfx/pokemon/mon_1BD/back.2bpp.lz"

SECTION "Pics 30", ROMX

Mon1BEFrontpic:      INCBIN "gfx/pokemon/mon_1BE/front.animated.2bpp.lz"
Mon1BEBackpic:       INCBIN "gfx/pokemon/mon_1BE/back.2bpp.lz"
Mon1BFFrontpic:      INCBIN "gfx/pokemon/mon_1BF/front.animated.2bpp.lz"
Mon1BFBackpic:       INCBIN "gfx/pokemon/mon_1BF/back.2bpp.lz"
Mon1C0Frontpic:      INCBIN "gfx/pokemon/mon_1C0/front.animated.2bpp.lz"
Mon1C0Backpic:       INCBIN "gfx/pokemon/mon_1C0/back.2bpp.lz"
Mon1C1Frontpic:      INCBIN "gfx/pokemon/mon_1C1/front.animated.2bpp.lz"
Mon1C1Backpic:       INCBIN "gfx/pokemon/mon_1C1/back.2bpp.lz"
Mon1C2Frontpic:      INCBIN "gfx/pokemon/mon_1C2/front.animated.2bpp.lz"
Mon1C2Backpic:       INCBIN "gfx/pokemon/mon_1C2/back.2bpp.lz"
Mon1C3Frontpic:      INCBIN "gfx/pokemon/mon_1C3/front.animated.2bpp.lz"
Mon1C3Backpic:       INCBIN "gfx/pokemon/mon_1C3/back.2bpp.lz"
Mon1C4Frontpic:      INCBIN "gfx/pokemon/mon_1C4/front.animated.2bpp.lz"
Mon1C4Backpic:       INCBIN "gfx/pokemon/mon_1C4/back.2bpp.lz"
Mon1C5Frontpic:      INCBIN "gfx/pokemon/mon_1C5/front.animated.2bpp.lz"
Mon1C5Backpic:       INCBIN "gfx/pokemon/mon_1C5/back.2bpp.lz"
Mon1C6Frontpic:      INCBIN "gfx/pokemon/mon_1C6/front.animated.2bpp.lz"
Mon1C6Backpic:       INCBIN "gfx/pokemon/mon_1C6/back.2bpp.lz"
Mon1C7Frontpic:      INCBIN "gfx/pokemon/mon_1C7/front.animated.2bpp.lz"
Mon1C7Backpic:       INCBIN "gfx/pokemon/mon_1C7/back.2bpp.lz"
Mon1C8Frontpic:      INCBIN "gfx/pokemon/mon_1C8/front.animated.2bpp.lz"
Mon1C8Backpic:       INCBIN "gfx/pokemon/mon_1C8/back.2bpp.lz"
Mon1C9Frontpic:      INCBIN "gfx/pokemon/mon_1C9/front.animated.2bpp.lz"
Mon1C9Backpic:       INCBIN "gfx/pokemon/mon_1C9/back.2bpp.lz"
Mon1CAFrontpic:      INCBIN "gfx/pokemon/mon_1CA/front.animated.2bpp.lz"
Mon1CABackpic:       INCBIN "gfx/pokemon/mon_1CA/back.2bpp.lz"
Mon1CBFrontpic:      INCBIN "gfx/pokemon/mon_1CB/front.animated.2bpp.lz"
Mon1CBBackpic:       INCBIN "gfx/pokemon/mon_1CB/back.2bpp.lz"
Mon1CCFrontpic:      INCBIN "gfx/pokemon/mon_1CC/front.animated.2bpp.lz"
Mon1CCBackpic:       INCBIN "gfx/pokemon/mon_1CC/back.2bpp.lz"
Mon1CDFrontpic:      INCBIN "gfx/pokemon/mon_1CD/front.animated.2bpp.lz"
Mon1CDBackpic:       INCBIN "gfx/pokemon/mon_1CD/back.2bpp.lz"
Mon1CEFrontpic:      INCBIN "gfx/pokemon/mon_1CE/front.animated.2bpp.lz"
Mon1CEBackpic:       INCBIN "gfx/pokemon/mon_1CE/back.2bpp.lz"
Mon1CFFrontpic:      INCBIN "gfx/pokemon/mon_1CF/front.animated.2bpp.lz"
Mon1CFBackpic:       INCBIN "gfx/pokemon/mon_1CF/back.2bpp.lz"
Mon1D0Frontpic:      INCBIN "gfx/pokemon/mon_1D0/front.animated.2bpp.lz"
Mon1D0Backpic:       INCBIN "gfx/pokemon/mon_1D0/back.2bpp.lz"
Mon1D1Frontpic:      INCBIN "gfx/pokemon/mon_1D1/front.animated.2bpp.lz"
Mon1D1Backpic:       INCBIN "gfx/pokemon/mon_1D1/back.2bpp.lz"
Mon1D2Frontpic:      INCBIN "gfx/pokemon/mon_1D2/front.animated.2bpp.lz"
Mon1D2Backpic:       INCBIN "gfx/pokemon/mon_1D2/back.2bpp.lz"
Mon1D3Frontpic:      INCBIN "gfx/pokemon/mon_1D3/front.animated.2bpp.lz"
Mon1D3Backpic:       INCBIN "gfx/pokemon/mon_1D3/back.2bpp.lz"
Mon1D4Frontpic:      INCBIN "gfx/pokemon/mon_1D4/front.animated.2bpp.lz"
Mon1D4Backpic:       INCBIN "gfx/pokemon/mon_1D4/back.2bpp.lz"
Mon1D5Frontpic:      INCBIN "gfx/pokemon/mon_1D5/front.animated.2bpp.lz"
Mon1D5Backpic:       INCBIN "gfx/pokemon/mon_1D5/back.2bpp.lz"

SECTION "Pics 31", ROMX

Mon1D6Frontpic:      INCBIN "gfx/pokemon/mon_1D6/front.animated.2bpp.lz"
Mon1D6Backpic:       INCBIN "gfx/pokemon/mon_1D6/back.2bpp.lz"
Mon1D7Frontpic:      INCBIN "gfx/pokemon/mon_1D7/front.animated.2bpp.lz"
Mon1D7Backpic:       INCBIN "gfx/pokemon/mon_1D7/back.2bpp.lz"
Mon1D8Frontpic:      INCBIN "gfx/pokemon/mon_1D8/front.animated.2bpp.lz"
Mon1D8Backpic:       INCBIN "gfx/pokemon/mon_1D8/back.2bpp.lz"
Mon1D9Frontpic:      INCBIN "gfx/pokemon/mon_1D9/front.animated.2bpp.lz"
Mon1D9Backpic:       INCBIN "gfx/pokemon/mon_1D9/back.2bpp.lz"
Mon1DAFrontpic:      INCBIN "gfx/pokemon/mon_1DA/front.animated.2bpp.lz"
Mon1DABackpic:       INCBIN "gfx/pokemon/mon_1DA/back.2bpp.lz"
Mon1DBFrontpic:      INCBIN "gfx/pokemon/mon_1DB/front.animated.2bpp.lz"
Mon1DBBackpic:       INCBIN "gfx/pokemon/mon_1DB/back.2bpp.lz"
Mon1DCFrontpic:      INCBIN "gfx/pokemon/mon_1DC/front.animated.2bpp.lz"
Mon1DCBackpic:       INCBIN "gfx/pokemon/mon_1DC/back.2bpp.lz"
Mon1DDFrontpic:      INCBIN "gfx/pokemon/mon_1DD/front.animated.2bpp.lz"
Mon1DDBackpic:       INCBIN "gfx/pokemon/mon_1DD/back.2bpp.lz"
Mon1DEFrontpic:      INCBIN "gfx/pokemon/mon_1DE/front.animated.2bpp.lz"
Mon1DEBackpic:       INCBIN "gfx/pokemon/mon_1DE/back.2bpp.lz"
Mon1DFFrontpic:      INCBIN "gfx/pokemon/mon_1DF/front.animated.2bpp.lz"
Mon1DFBackpic:       INCBIN "gfx/pokemon/mon_1DF/back.2bpp.lz"
Mon1E0Frontpic:      INCBIN "gfx/pokemon/mon_1E0/front.animated.2bpp.lz"
Mon1E0Backpic:       INCBIN "gfx/pokemon/mon_1E0/back.2bpp.lz"
Mon1E1Frontpic:      INCBIN "gfx/pokemon/mon_1E1/front.animated.2bpp.lz"
Mon1E1Backpic:       INCBIN "gfx/pokemon/mon_1E1/back.2bpp.lz"
Mon1E2Frontpic:      INCBIN "gfx/pokemon/mon_1E2/front.animated.2bpp.lz"
Mon1E2Backpic:       INCBIN "gfx/pokemon/mon_1E2/back.2bpp.lz"
Mon1E3Frontpic:      INCBIN "gfx/pokemon/mon_1E3/front.animated.2bpp.lz"
Mon1E3Backpic:       INCBIN "gfx/pokemon/mon_1E3/back.2bpp.lz"
Mon1E4Frontpic:      INCBIN "gfx/pokemon/mon_1E4/front.animated.2bpp.lz"
Mon1E4Backpic:       INCBIN "gfx/pokemon/mon_1E4/back.2bpp.lz"
Mon1E5Frontpic:      INCBIN "gfx/pokemon/mon_1E5/front.animated.2bpp.lz"
Mon1E5Backpic:       INCBIN "gfx/pokemon/mon_1E5/back.2bpp.lz"
Mon1E6Frontpic:      INCBIN "gfx/pokemon/mon_1E6/front.animated.2bpp.lz"
Mon1E6Backpic:       INCBIN "gfx/pokemon/mon_1E6/back.2bpp.lz"
Mon1E7Frontpic:      INCBIN "gfx/pokemon/mon_1E7/front.animated.2bpp.lz"
Mon1E7Backpic:       INCBIN "gfx/pokemon/mon_1E7/back.2bpp.lz"
Mon1E8Frontpic:      INCBIN "gfx/pokemon/mon_1E8/front.animated.2bpp.lz"
Mon1E8Backpic:       INCBIN "gfx/pokemon/mon_1E8/back.2bpp.lz"
Mon1E9Frontpic:      INCBIN "gfx/pokemon/mon_1E9/front.animated.2bpp.lz"
Mon1E9Backpic:       INCBIN "gfx/pokemon/mon_1E9/back.2bpp.lz"
Mon1EAFrontpic:      INCBIN "gfx/pokemon/mon_1EA/front.animated.2bpp.lz"
Mon1EABackpic:       INCBIN "gfx/pokemon/mon_1EA/back.2bpp.lz"
Mon1EBFrontpic:      INCBIN "gfx/pokemon/mon_1EB/front.animated.2bpp.lz"
Mon1EBBackpic:       INCBIN "gfx/pokemon/mon_1EB/back.2bpp.lz"
Mon1ECFrontpic:      INCBIN "gfx/pokemon/mon_1EC/front.animated.2bpp.lz"
Mon1ECBackpic:       INCBIN "gfx/pokemon/mon_1EC/back.2bpp.lz"
Mon1EDFrontpic:      INCBIN "gfx/pokemon/mon_1ED/front.animated.2bpp.lz"
Mon1EDBackpic:       INCBIN "gfx/pokemon/mon_1ED/back.2bpp.lz"

SECTION "Pics 32", ROMX

Mon1EEFrontpic:      INCBIN "gfx/pokemon/mon_1EE/front.animated.2bpp.lz"
Mon1EEBackpic:       INCBIN "gfx/pokemon/mon_1EE/back.2bpp.lz"
Mon1EFFrontpic:      INCBIN "gfx/pokemon/mon_1EF/front.animated.2bpp.lz"
Mon1EFBackpic:       INCBIN "gfx/pokemon/mon_1EF/back.2bpp.lz"
Mon1F0Frontpic:      INCBIN "gfx/pokemon/mon_1F0/front.animated.2bpp.lz"
Mon1F0Backpic:       INCBIN "gfx/pokemon/mon_1F0/back.2bpp.lz"
Mon1F1Frontpic:      INCBIN "gfx/pokemon/mon_1F1/front.animated.2bpp.lz"
Mon1F1Backpic:       INCBIN "gfx/pokemon/mon_1F1/back.2bpp.lz"
Mon1F2Frontpic:      INCBIN "gfx/pokemon/mon_1F2/front.animated.2bpp.lz"
Mon1F2Backpic:       INCBIN "gfx/pokemon/mon_1F2/back.2bpp.lz"
Mon1F3Frontpic:      INCBIN "gfx/pokemon/mon_1F3/front.animated.2bpp.lz"
Mon1F3Backpic:       INCBIN "gfx/pokemon/mon_1F3/back.2bpp.lz"
Mon1F4Frontpic:      INCBIN "gfx/pokemon/mon_1F4/front.animated.2bpp.lz"
Mon1F4Backpic:       INCBIN "gfx/pokemon/mon_1F4/back.2bpp.lz"
Mon1F5Frontpic:      INCBIN "gfx/pokemon/mon_1F5/front.animated.2bpp.lz"
Mon1F5Backpic:       INCBIN "gfx/pokemon/mon_1F5/back.2bpp.lz"
Mon1F6Frontpic:      INCBIN "gfx/pokemon/mon_1F6/front.animated.2bpp.lz"
Mon1F6Backpic:       INCBIN "gfx/pokemon/mon_1F6/back.2bpp.lz"
Mon1F7Frontpic:      INCBIN "gfx/pokemon/mon_1F7/front.animated.2bpp.lz"
Mon1F7Backpic:       INCBIN "gfx/pokemon/mon_1F7/back.2bpp.lz"
Mon1F8Frontpic:      INCBIN "gfx/pokemon/mon_1F8/front.animated.2bpp.lz"
Mon1F8Backpic:       INCBIN "gfx/pokemon/mon_1F8/back.2bpp.lz"
Mon1F9Frontpic:      INCBIN "gfx/pokemon/mon_1F9/front.animated.2bpp.lz"
Mon1F9Backpic:       INCBIN "gfx/pokemon/mon_1F9/back.2bpp.lz"
Mon1FAFrontpic:      INCBIN "gfx/pokemon/mon_1FA/front.animated.2bpp.lz"
Mon1FABackpic:       INCBIN "gfx/pokemon/mon_1FA/back.2bpp.lz"
Mon1FBFrontpic:      INCBIN "gfx/pokemon/mon_1FB/front.animated.2bpp.lz"
Mon1FBBackpic:       INCBIN "gfx/pokemon/mon_1FB/back.2bpp.lz"
Mon1FCFrontpic:      INCBIN "gfx/pokemon/mon_1FC/front.animated.2bpp.lz"
Mon1FCBackpic:       INCBIN "gfx/pokemon/mon_1FC/back.2bpp.lz"
Mon1FDFrontpic:      INCBIN "gfx/pokemon/mon_1FD/front.animated.2bpp.lz"
Mon1FDBackpic:       INCBIN "gfx/pokemon/mon_1FD/back.2bpp.lz"
